import { ObjectInterpolation } from "@emotion/core";

const tokensUntyped = {
  _m_1: { margin: "-0.25rem" },
  _m_10: { margin: "-2.5rem" },
  _m_12: { margin: "-3rem" },
  _m_16: { margin: "-4rem" },
  _m_2: { margin: "-0.5rem" },
  _m_20: { margin: "-5rem" },
  _m_24: { margin: "-6rem" },
  _m_3: { margin: "-0.75rem" },
  _m_32: { margin: "-8rem" },
  _m_4: { margin: "-1rem" },
  _m_40: { margin: "-10rem" },
  _m_48: { margin: "-12rem" },
  _m_5: { margin: "-1.25rem" },
  _m_56: { margin: "-14rem" },
  _m_6: { margin: "-1.5rem" },
  _m_64: { margin: "-16rem" },
  _m_8: { margin: "-2rem" },
  _m_px: { margin: "-1px" },
  _mb_1: { marginBottom: "-0.25rem" },
  _mb_10: { marginBottom: "-2.5rem" },
  _mb_12: { marginBottom: "-3rem" },
  _mb_16: { marginBottom: "-4rem" },
  _mb_2: { marginBottom: "-0.5rem" },
  _mb_20: { marginBottom: "-5rem" },
  _mb_24: { marginBottom: "-6rem" },
  _mb_3: { marginBottom: "-0.75rem" },
  _mb_32: { marginBottom: "-8rem" },
  _mb_4: { marginBottom: "-1rem" },
  _mb_40: { marginBottom: "-10rem" },
  _mb_48: { marginBottom: "-12rem" },
  _mb_5: { marginBottom: "-1.25rem" },
  _mb_56: { marginBottom: "-14rem" },
  _mb_6: { marginBottom: "-1.5rem" },
  _mb_64: { marginBottom: "-16rem" },
  _mb_8: { marginBottom: "-2rem" },
  _mb_px: { marginBottom: "-1px" },
  _ml_1: { marginLeft: "-0.25rem" },
  _ml_10: { marginLeft: "-2.5rem" },
  _ml_12: { marginLeft: "-3rem" },
  _ml_16: { marginLeft: "-4rem" },
  _ml_2: { marginLeft: "-0.5rem" },
  _ml_20: { marginLeft: "-5rem" },
  _ml_24: { marginLeft: "-6rem" },
  _ml_3: { marginLeft: "-0.75rem" },
  _ml_32: { marginLeft: "-8rem" },
  _ml_4: { marginLeft: "-1rem" },
  _ml_40: { marginLeft: "-10rem" },
  _ml_48: { marginLeft: "-12rem" },
  _ml_5: { marginLeft: "-1.25rem" },
  _ml_56: { marginLeft: "-14rem" },
  _ml_6: { marginLeft: "-1.5rem" },
  _ml_64: { marginLeft: "-16rem" },
  _ml_8: { marginLeft: "-2rem" },
  _ml_px: { marginLeft: "-1px" },
  _mr_1: { marginRight: "-0.25rem" },
  _mr_10: { marginRight: "-2.5rem" },
  _mr_12: { marginRight: "-3rem" },
  _mr_16: { marginRight: "-4rem" },
  _mr_2: { marginRight: "-0.5rem" },
  _mr_20: { marginRight: "-5rem" },
  _mr_24: { marginRight: "-6rem" },
  _mr_3: { marginRight: "-0.75rem" },
  _mr_32: { marginRight: "-8rem" },
  _mr_4: { marginRight: "-1rem" },
  _mr_40: { marginRight: "-10rem" },
  _mr_48: { marginRight: "-12rem" },
  _mr_5: { marginRight: "-1.25rem" },
  _mr_56: { marginRight: "-14rem" },
  _mr_6: { marginRight: "-1.5rem" },
  _mr_64: { marginRight: "-16rem" },
  _mr_8: { marginRight: "-2rem" },
  _mr_px: { marginRight: "-1px" },
  _mt_1: { marginTop: "-0.25rem" },
  _mt_10: { marginTop: "-2.5rem" },
  _mt_12: { marginTop: "-3rem" },
  _mt_16: { marginTop: "-4rem" },
  _mt_2: { marginTop: "-0.5rem" },
  _mt_20: { marginTop: "-5rem" },
  _mt_24: { marginTop: "-6rem" },
  _mt_3: { marginTop: "-0.75rem" },
  _mt_32: { marginTop: "-8rem" },
  _mt_4: { marginTop: "-1rem" },
  _mt_40: { marginTop: "-10rem" },
  _mt_48: { marginTop: "-12rem" },
  _mt_5: { marginTop: "-1.25rem" },
  _mt_56: { marginTop: "-14rem" },
  _mt_6: { marginTop: "-1.5rem" },
  _mt_64: { marginTop: "-16rem" },
  _mt_8: { marginTop: "-2rem" },
  _mt_px: { marginTop: "-1px" },
  _mx_1: { marginLeft: "-0.25rem", marginRight: "-0.25rem" },
  _mx_10: { marginLeft: "-2.5rem", marginRight: "-2.5rem" },
  _mx_12: { marginLeft: "-3rem", marginRight: "-3rem" },
  _mx_16: { marginLeft: "-4rem", marginRight: "-4rem" },
  _mx_2: { marginLeft: "-0.5rem", marginRight: "-0.5rem" },
  _mx_20: { marginLeft: "-5rem", marginRight: "-5rem" },
  _mx_24: { marginLeft: "-6rem", marginRight: "-6rem" },
  _mx_3: { marginLeft: "-0.75rem", marginRight: "-0.75rem" },
  _mx_32: { marginLeft: "-8rem", marginRight: "-8rem" },
  _mx_4: { marginLeft: "-1rem", marginRight: "-1rem" },
  _mx_40: { marginLeft: "-10rem", marginRight: "-10rem" },
  _mx_48: { marginLeft: "-12rem", marginRight: "-12rem" },
  _mx_5: { marginLeft: "-1.25rem", marginRight: "-1.25rem" },
  _mx_56: { marginLeft: "-14rem", marginRight: "-14rem" },
  _mx_6: { marginLeft: "-1.5rem", marginRight: "-1.5rem" },
  _mx_64: { marginLeft: "-16rem", marginRight: "-16rem" },
  _mx_8: { marginLeft: "-2rem", marginRight: "-2rem" },
  _mx_px: { marginLeft: "-1px", marginRight: "-1px" },
  _my_1: { marginTop: "-0.25rem", marginBottom: "-0.25rem" },
  _my_10: { marginTop: "-2.5rem", marginBottom: "-2.5rem" },
  _my_12: { marginTop: "-3rem", marginBottom: "-3rem" },
  _my_16: { marginTop: "-4rem", marginBottom: "-4rem" },
  _my_2: { marginTop: "-0.5rem", marginBottom: "-0.5rem" },
  _my_20: { marginTop: "-5rem", marginBottom: "-5rem" },
  _my_24: { marginTop: "-6rem", marginBottom: "-6rem" },
  _my_3: { marginTop: "-0.75rem", marginBottom: "-0.75rem" },
  _my_32: { marginTop: "-8rem", marginBottom: "-8rem" },
  _my_4: { marginTop: "-1rem", marginBottom: "-1rem" },
  _my_40: { marginTop: "-10rem", marginBottom: "-10rem" },
  _my_48: { marginTop: "-12rem", marginBottom: "-12rem" },
  _my_5: { marginTop: "-1.25rem", marginBottom: "-1.25rem" },
  _my_56: { marginTop: "-14rem", marginBottom: "-14rem" },
  _my_6: { marginTop: "-1.5rem", marginBottom: "-1.5rem" },
  _my_64: { marginTop: "-16rem", marginBottom: "-16rem" },
  _my_8: { marginTop: "-2rem", marginBottom: "-2rem" },
  _my_px: { marginTop: "-1px", marginBottom: "-1px" },
  absolute: { position: "absolute" },
  align_baseline: { verticalAlign: "baseline" },
  align_bottom: { verticalAlign: "bottom" },
  align_middle: { verticalAlign: "middle" },
  align_text_bottom: { verticalAlign: "text-bottom" },
  align_text_top: { verticalAlign: "text-top" },
  align_top: { verticalAlign: "top" },
  antialiased: {
    WebkitFontSmoothing: "antialiased",
    MozOsxFontSmoothing: "grayscale"
  },
  appearance_none: {
    WebkitAppearance: "none",
    MozAppearance: "none",
    appearance: "none"
  },
  bg_auto: { backgroundSize: "auto" },
  bg_black: { backgroundColor: "#000" },
  bg_blue_100: { backgroundColor: "#ebf8ff" },
  bg_blue_200: { backgroundColor: "#bee3f8" },
  bg_blue_300: { backgroundColor: "#90cdf4" },
  bg_blue_400: { backgroundColor: "#63b3ed" },
  bg_blue_500: { backgroundColor: "#4299e1" },
  bg_blue_600: { backgroundColor: "#3182ce" },
  bg_blue_700: { backgroundColor: "#2b6cb0" },
  bg_blue_800: { backgroundColor: "#2c5282" },
  bg_blue_900: { backgroundColor: "#2a4365" },
  bg_bottom: { backgroundPosition: "bottom" },
  bg_center: { backgroundPosition: "center" },
  bg_contain: { backgroundSize: "contain" },
  bg_cover: { backgroundSize: "cover" },
  bg_fixed: { backgroundAttachment: "fixed" },
  bg_gray_100: { backgroundColor: "#f7fafc" },
  bg_gray_200: { backgroundColor: "#edf2f7" },
  bg_gray_300: { backgroundColor: "#e2e8f0" },
  bg_gray_400: { backgroundColor: "#cbd5e0" },
  bg_gray_500: { backgroundColor: "#a0aec0" },
  bg_gray_600: { backgroundColor: "#718096" },
  bg_gray_700: { backgroundColor: "#4a5568" },
  bg_gray_800: { backgroundColor: "#2d3748" },
  bg_gray_900: { backgroundColor: "#1a202c" },
  bg_green_100: { backgroundColor: "#f0fff4" },
  bg_green_200: { backgroundColor: "#c6f6d5" },
  bg_green_300: { backgroundColor: "#9ae6b4" },
  bg_green_400: { backgroundColor: "#68d391" },
  bg_green_500: { backgroundColor: "#48bb78" },
  bg_green_600: { backgroundColor: "#38a169" },
  bg_green_700: { backgroundColor: "#2f855a" },
  bg_green_800: { backgroundColor: "#276749" },
  bg_green_900: { backgroundColor: "#22543d" },
  bg_indigo_100: { backgroundColor: "#ebf4ff" },
  bg_indigo_200: { backgroundColor: "#c3dafe" },
  bg_indigo_300: { backgroundColor: "#a3bffa" },
  bg_indigo_400: { backgroundColor: "#7f9cf5" },
  bg_indigo_500: { backgroundColor: "#667eea" },
  bg_indigo_600: { backgroundColor: "#5a67d8" },
  bg_indigo_700: { backgroundColor: "#4c51bf" },
  bg_indigo_800: { backgroundColor: "#434190" },
  bg_indigo_900: { backgroundColor: "#3c366b" },
  bg_left: { backgroundPosition: "left" },
  bg_left_bottom: { backgroundPosition: "left bottom" },
  bg_left_top: { backgroundPosition: "left top" },
  bg_local: { backgroundAttachment: "local" },
  bg_no_repeat: { backgroundRepeat: "no-repeat" },
  bg_orange_100: { backgroundColor: "#fffaf0" },
  bg_orange_200: { backgroundColor: "#feebc8" },
  bg_orange_300: { backgroundColor: "#fbd38d" },
  bg_orange_400: { backgroundColor: "#f6ad55" },
  bg_orange_500: { backgroundColor: "#ed8936" },
  bg_orange_600: { backgroundColor: "#dd6b20" },
  bg_orange_700: { backgroundColor: "#c05621" },
  bg_orange_800: { backgroundColor: "#9c4221" },
  bg_orange_900: { backgroundColor: "#7b341e" },
  bg_pink_100: { backgroundColor: "#fff5f7" },
  bg_pink_200: { backgroundColor: "#fed7e2" },
  bg_pink_300: { backgroundColor: "#fbb6ce" },
  bg_pink_400: { backgroundColor: "#f687b3" },
  bg_pink_500: { backgroundColor: "#ed64a6" },
  bg_pink_600: { backgroundColor: "#d53f8c" },
  bg_pink_700: { backgroundColor: "#b83280" },
  bg_pink_800: { backgroundColor: "#97266d" },
  bg_pink_900: { backgroundColor: "#702459" },
  bg_purple_100: { backgroundColor: "#faf5ff" },
  bg_purple_200: { backgroundColor: "#e9d8fd" },
  bg_purple_300: { backgroundColor: "#d6bcfa" },
  bg_purple_400: { backgroundColor: "#b794f4" },
  bg_purple_500: { backgroundColor: "#9f7aea" },
  bg_purple_600: { backgroundColor: "#805ad5" },
  bg_purple_700: { backgroundColor: "#6b46c1" },
  bg_purple_800: { backgroundColor: "#553c9a" },
  bg_purple_900: { backgroundColor: "#44337a" },
  bg_red_100: { backgroundColor: "#fff5f5" },
  bg_red_200: { backgroundColor: "#fed7d7" },
  bg_red_300: { backgroundColor: "#feb2b2" },
  bg_red_400: { backgroundColor: "#fc8181" },
  bg_red_500: { backgroundColor: "#f56565" },
  bg_red_600: { backgroundColor: "#e53e3e" },
  bg_red_700: { backgroundColor: "#c53030" },
  bg_red_800: { backgroundColor: "#9b2c2c" },
  bg_red_900: { backgroundColor: "#742a2a" },
  bg_repeat: { backgroundRepeat: "repeat" },
  bg_repeat_round: { backgroundRepeat: "round" },
  bg_repeat_space: { backgroundRepeat: "space" },
  bg_repeat_x: { backgroundRepeat: "repeat-x" },
  bg_repeat_y: { backgroundRepeat: "repeat-y" },
  bg_right: { backgroundPosition: "right" },
  bg_right_bottom: { backgroundPosition: "right bottom" },
  bg_right_top: { backgroundPosition: "right top" },
  bg_scroll: { backgroundAttachment: "scroll" },
  bg_teal_100: { backgroundColor: "#e6fffa" },
  bg_teal_200: { backgroundColor: "#b2f5ea" },
  bg_teal_300: { backgroundColor: "#81e6d9" },
  bg_teal_400: { backgroundColor: "#4fd1c5" },
  bg_teal_500: { backgroundColor: "#38b2ac" },
  bg_teal_600: { backgroundColor: "#319795" },
  bg_teal_700: { backgroundColor: "#2c7a7b" },
  bg_teal_800: { backgroundColor: "#285e61" },
  bg_teal_900: { backgroundColor: "#234e52" },
  bg_top: { backgroundPosition: "top" },
  bg_transparent: { backgroundColor: "transparent" },
  bg_white: { backgroundColor: "#fff" },
  bg_yellow_100: { backgroundColor: "#fffff0" },
  bg_yellow_200: { backgroundColor: "#fefcbf" },
  bg_yellow_300: { backgroundColor: "#faf089" },
  bg_yellow_400: { backgroundColor: "#f6e05e" },
  bg_yellow_500: { backgroundColor: "#ecc94b" },
  bg_yellow_600: { backgroundColor: "#d69e2e" },
  bg_yellow_700: { backgroundColor: "#b7791f" },
  bg_yellow_800: { backgroundColor: "#975a16" },
  bg_yellow_900: { backgroundColor: "#744210" },
  block: { display: "block" },
  border: { borderWidth: "1px" },
  border_0: { borderWidth: "0" },
  border_2: { borderWidth: "2px" },
  border_4: { borderWidth: "4px" },
  border_8: { borderWidth: "8px" },
  border_b: { borderBottomWidth: "1px" },
  border_b_0: { borderBottomWidth: "0" },
  border_b_2: { borderBottomWidth: "2px" },
  border_b_4: { borderBottomWidth: "4px" },
  border_b_8: { borderBottomWidth: "8px" },
  border_black: { borderColor: "#000" },
  border_blue_100: { borderColor: "#ebf8ff" },
  border_blue_200: { borderColor: "#bee3f8" },
  border_blue_300: { borderColor: "#90cdf4" },
  border_blue_400: { borderColor: "#63b3ed" },
  border_blue_500: { borderColor: "#4299e1" },
  border_blue_600: { borderColor: "#3182ce" },
  border_blue_700: { borderColor: "#2b6cb0" },
  border_blue_800: { borderColor: "#2c5282" },
  border_blue_900: { borderColor: "#2a4365" },
  border_collapse: { borderCollapse: "collapse" },
  border_dashed: { borderStyle: "dashed" },
  border_dotted: { borderStyle: "dotted" },
  border_double: { borderStyle: "double" },
  border_gray_100: { borderColor: "#f7fafc" },
  border_gray_200: { borderColor: "#edf2f7" },
  border_gray_300: { borderColor: "#e2e8f0" },
  border_gray_400: { borderColor: "#cbd5e0" },
  border_gray_500: { borderColor: "#a0aec0" },
  border_gray_600: { borderColor: "#718096" },
  border_gray_700: { borderColor: "#4a5568" },
  border_gray_800: { borderColor: "#2d3748" },
  border_gray_900: { borderColor: "#1a202c" },
  border_green_100: { borderColor: "#f0fff4" },
  border_green_200: { borderColor: "#c6f6d5" },
  border_green_300: { borderColor: "#9ae6b4" },
  border_green_400: { borderColor: "#68d391" },
  border_green_500: { borderColor: "#48bb78" },
  border_green_600: { borderColor: "#38a169" },
  border_green_700: { borderColor: "#2f855a" },
  border_green_800: { borderColor: "#276749" },
  border_green_900: { borderColor: "#22543d" },
  border_indigo_100: { borderColor: "#ebf4ff" },
  border_indigo_200: { borderColor: "#c3dafe" },
  border_indigo_300: { borderColor: "#a3bffa" },
  border_indigo_400: { borderColor: "#7f9cf5" },
  border_indigo_500: { borderColor: "#667eea" },
  border_indigo_600: { borderColor: "#5a67d8" },
  border_indigo_700: { borderColor: "#4c51bf" },
  border_indigo_800: { borderColor: "#434190" },
  border_indigo_900: { borderColor: "#3c366b" },
  border_l: { borderLeftWidth: "1px" },
  border_l_0: { borderLeftWidth: "0" },
  border_l_2: { borderLeftWidth: "2px" },
  border_l_4: { borderLeftWidth: "4px" },
  border_l_8: { borderLeftWidth: "8px" },
  border_none: { borderStyle: "none" },
  border_orange_100: { borderColor: "#fffaf0" },
  border_orange_200: { borderColor: "#feebc8" },
  border_orange_300: { borderColor: "#fbd38d" },
  border_orange_400: { borderColor: "#f6ad55" },
  border_orange_500: { borderColor: "#ed8936" },
  border_orange_600: { borderColor: "#dd6b20" },
  border_orange_700: { borderColor: "#c05621" },
  border_orange_800: { borderColor: "#9c4221" },
  border_orange_900: { borderColor: "#7b341e" },
  border_pink_100: { borderColor: "#fff5f7" },
  border_pink_200: { borderColor: "#fed7e2" },
  border_pink_300: { borderColor: "#fbb6ce" },
  border_pink_400: { borderColor: "#f687b3" },
  border_pink_500: { borderColor: "#ed64a6" },
  border_pink_600: { borderColor: "#d53f8c" },
  border_pink_700: { borderColor: "#b83280" },
  border_pink_800: { borderColor: "#97266d" },
  border_pink_900: { borderColor: "#702459" },
  border_purple_100: { borderColor: "#faf5ff" },
  border_purple_200: { borderColor: "#e9d8fd" },
  border_purple_300: { borderColor: "#d6bcfa" },
  border_purple_400: { borderColor: "#b794f4" },
  border_purple_500: { borderColor: "#9f7aea" },
  border_purple_600: { borderColor: "#805ad5" },
  border_purple_700: { borderColor: "#6b46c1" },
  border_purple_800: { borderColor: "#553c9a" },
  border_purple_900: { borderColor: "#44337a" },
  border_r: { borderRightWidth: "1px" },
  border_r_0: { borderRightWidth: "0" },
  border_r_2: { borderRightWidth: "2px" },
  border_r_4: { borderRightWidth: "4px" },
  border_r_8: { borderRightWidth: "8px" },
  border_red_100: { borderColor: "#fff5f5" },
  border_red_200: { borderColor: "#fed7d7" },
  border_red_300: { borderColor: "#feb2b2" },
  border_red_400: { borderColor: "#fc8181" },
  border_red_500: { borderColor: "#f56565" },
  border_red_600: { borderColor: "#e53e3e" },
  border_red_700: { borderColor: "#c53030" },
  border_red_800: { borderColor: "#9b2c2c" },
  border_red_900: { borderColor: "#742a2a" },
  border_separate: { borderCollapse: "separate" },
  border_solid: { borderStyle: "solid" },
  border_t: { borderTopWidth: "1px" },
  border_t_0: { borderTopWidth: "0" },
  border_t_2: { borderTopWidth: "2px" },
  border_t_4: { borderTopWidth: "4px" },
  border_t_8: { borderTopWidth: "8px" },
  border_teal_100: { borderColor: "#e6fffa" },
  border_teal_200: { borderColor: "#b2f5ea" },
  border_teal_300: { borderColor: "#81e6d9" },
  border_teal_400: { borderColor: "#4fd1c5" },
  border_teal_500: { borderColor: "#38b2ac" },
  border_teal_600: { borderColor: "#319795" },
  border_teal_700: { borderColor: "#2c7a7b" },
  border_teal_800: { borderColor: "#285e61" },
  border_teal_900: { borderColor: "#234e52" },
  border_transparent: { borderColor: "transparent" },
  border_white: { borderColor: "#fff" },
  border_yellow_100: { borderColor: "#fffff0" },
  border_yellow_200: { borderColor: "#fefcbf" },
  border_yellow_300: { borderColor: "#faf089" },
  border_yellow_400: { borderColor: "#f6e05e" },
  border_yellow_500: { borderColor: "#ecc94b" },
  border_yellow_600: { borderColor: "#d69e2e" },
  border_yellow_700: { borderColor: "#b7791f" },
  border_yellow_800: { borderColor: "#975a16" },
  border_yellow_900: { borderColor: "#744210" },
  bottom_0: { bottom: "0" },
  bottom_auto: { bottom: "auto" },
  break_all: { wordBreak: "break-all" },
  break_normal: { overflowWrap: "normal", wordBreak: "normal" },
  break_words: { overflowWrap: "break-word" },
  capitalize: { textTransform: "capitalize" },
  content_around: { alignContent: "space-around" },
  content_between: { alignContent: "space-between" },
  content_center: { alignContent: "center" },
  content_end: { alignContent: "flex-end" },
  content_start: { alignContent: "flex-start" },
  cursor_auto: { cursor: "auto" },
  cursor_default: { cursor: "default" },
  cursor_move: { cursor: "move" },
  cursor_not_allowed: { cursor: "not-allowed" },
  cursor_pointer: { cursor: "pointer" },
  cursor_text: { cursor: "text" },
  cursor_wait: { cursor: "wait" },
  fill_current: { fill: "currentColor" },
  fixed: { position: "fixed" },
  flex: { display: ["-webkit-box", "flex"] },
  flex_1: { WebkitBoxFlex: "1", flex: "1 1 0%" },
  flex_auto: { WebkitBoxFlex: "1", flex: "1 1 auto" },
  flex_col: {
    WebkitBoxOrient: "vertical",
    WebkitBoxDirection: "normal",
    flexDirection: "column"
  },
  flex_col_reverse: {
    WebkitBoxOrient: "vertical",
    WebkitBoxDirection: "reverse",
    flexDirection: "column-reverse"
  },
  flex_grow: { WebkitBoxFlex: "1", flexGrow: "1" },
  flex_grow_0: { WebkitBoxFlex: "0", flexGrow: "0" },
  flex_initial: { WebkitBoxFlex: "0", flex: "0 1 auto" },
  flex_no_wrap: { flexWrap: "nowrap" },
  flex_none: { WebkitBoxFlex: "0", flex: "none" },
  flex_row: {
    WebkitBoxOrient: "horizontal",
    WebkitBoxDirection: "normal",
    flexDirection: "row"
  },
  flex_row_reverse: {
    WebkitBoxOrient: "horizontal",
    WebkitBoxDirection: "reverse",
    flexDirection: "row-reverse"
  },
  flex_shrink: { flexShrink: "1" },
  flex_shrink_0: { flexShrink: "0" },
  flex_wrap: { flexWrap: "wrap" },
  flex_wrap_reverse: { flexWrap: "wrap-reverse" },
  float_left: { cssFloat: "left" },
  float_none: { cssFloat: "none" },
  float_right: { cssFloat: "right" },
  focus_bg_black: { "&:focus": { backgroundColor: "#000" } },
  focus_bg_blue_100: { "&:focus": { backgroundColor: "#ebf8ff" } },
  focus_bg_blue_200: { "&:focus": { backgroundColor: "#bee3f8" } },
  focus_bg_blue_300: { "&:focus": { backgroundColor: "#90cdf4" } },
  focus_bg_blue_400: { "&:focus": { backgroundColor: "#63b3ed" } },
  focus_bg_blue_500: { "&:focus": { backgroundColor: "#4299e1" } },
  focus_bg_blue_600: { "&:focus": { backgroundColor: "#3182ce" } },
  focus_bg_blue_700: { "&:focus": { backgroundColor: "#2b6cb0" } },
  focus_bg_blue_800: { "&:focus": { backgroundColor: "#2c5282" } },
  focus_bg_blue_900: { "&:focus": { backgroundColor: "#2a4365" } },
  focus_bg_gray_100: { "&:focus": { backgroundColor: "#f7fafc" } },
  focus_bg_gray_200: { "&:focus": { backgroundColor: "#edf2f7" } },
  focus_bg_gray_300: { "&:focus": { backgroundColor: "#e2e8f0" } },
  focus_bg_gray_400: { "&:focus": { backgroundColor: "#cbd5e0" } },
  focus_bg_gray_500: { "&:focus": { backgroundColor: "#a0aec0" } },
  focus_bg_gray_600: { "&:focus": { backgroundColor: "#718096" } },
  focus_bg_gray_700: { "&:focus": { backgroundColor: "#4a5568" } },
  focus_bg_gray_800: { "&:focus": { backgroundColor: "#2d3748" } },
  focus_bg_gray_900: { "&:focus": { backgroundColor: "#1a202c" } },
  focus_bg_green_100: { "&:focus": { backgroundColor: "#f0fff4" } },
  focus_bg_green_200: { "&:focus": { backgroundColor: "#c6f6d5" } },
  focus_bg_green_300: { "&:focus": { backgroundColor: "#9ae6b4" } },
  focus_bg_green_400: { "&:focus": { backgroundColor: "#68d391" } },
  focus_bg_green_500: { "&:focus": { backgroundColor: "#48bb78" } },
  focus_bg_green_600: { "&:focus": { backgroundColor: "#38a169" } },
  focus_bg_green_700: { "&:focus": { backgroundColor: "#2f855a" } },
  focus_bg_green_800: { "&:focus": { backgroundColor: "#276749" } },
  focus_bg_green_900: { "&:focus": { backgroundColor: "#22543d" } },
  focus_bg_indigo_100: { "&:focus": { backgroundColor: "#ebf4ff" } },
  focus_bg_indigo_200: { "&:focus": { backgroundColor: "#c3dafe" } },
  focus_bg_indigo_300: { "&:focus": { backgroundColor: "#a3bffa" } },
  focus_bg_indigo_400: { "&:focus": { backgroundColor: "#7f9cf5" } },
  focus_bg_indigo_500: { "&:focus": { backgroundColor: "#667eea" } },
  focus_bg_indigo_600: { "&:focus": { backgroundColor: "#5a67d8" } },
  focus_bg_indigo_700: { "&:focus": { backgroundColor: "#4c51bf" } },
  focus_bg_indigo_800: { "&:focus": { backgroundColor: "#434190" } },
  focus_bg_indigo_900: { "&:focus": { backgroundColor: "#3c366b" } },
  focus_bg_orange_100: { "&:focus": { backgroundColor: "#fffaf0" } },
  focus_bg_orange_200: { "&:focus": { backgroundColor: "#feebc8" } },
  focus_bg_orange_300: { "&:focus": { backgroundColor: "#fbd38d" } },
  focus_bg_orange_400: { "&:focus": { backgroundColor: "#f6ad55" } },
  focus_bg_orange_500: { "&:focus": { backgroundColor: "#ed8936" } },
  focus_bg_orange_600: { "&:focus": { backgroundColor: "#dd6b20" } },
  focus_bg_orange_700: { "&:focus": { backgroundColor: "#c05621" } },
  focus_bg_orange_800: { "&:focus": { backgroundColor: "#9c4221" } },
  focus_bg_orange_900: { "&:focus": { backgroundColor: "#7b341e" } },
  focus_bg_pink_100: { "&:focus": { backgroundColor: "#fff5f7" } },
  focus_bg_pink_200: { "&:focus": { backgroundColor: "#fed7e2" } },
  focus_bg_pink_300: { "&:focus": { backgroundColor: "#fbb6ce" } },
  focus_bg_pink_400: { "&:focus": { backgroundColor: "#f687b3" } },
  focus_bg_pink_500: { "&:focus": { backgroundColor: "#ed64a6" } },
  focus_bg_pink_600: { "&:focus": { backgroundColor: "#d53f8c" } },
  focus_bg_pink_700: { "&:focus": { backgroundColor: "#b83280" } },
  focus_bg_pink_800: { "&:focus": { backgroundColor: "#97266d" } },
  focus_bg_pink_900: { "&:focus": { backgroundColor: "#702459" } },
  focus_bg_purple_100: { "&:focus": { backgroundColor: "#faf5ff" } },
  focus_bg_purple_200: { "&:focus": { backgroundColor: "#e9d8fd" } },
  focus_bg_purple_300: { "&:focus": { backgroundColor: "#d6bcfa" } },
  focus_bg_purple_400: { "&:focus": { backgroundColor: "#b794f4" } },
  focus_bg_purple_500: { "&:focus": { backgroundColor: "#9f7aea" } },
  focus_bg_purple_600: { "&:focus": { backgroundColor: "#805ad5" } },
  focus_bg_purple_700: { "&:focus": { backgroundColor: "#6b46c1" } },
  focus_bg_purple_800: { "&:focus": { backgroundColor: "#553c9a" } },
  focus_bg_purple_900: { "&:focus": { backgroundColor: "#44337a" } },
  focus_bg_red_100: { "&:focus": { backgroundColor: "#fff5f5" } },
  focus_bg_red_200: { "&:focus": { backgroundColor: "#fed7d7" } },
  focus_bg_red_300: { "&:focus": { backgroundColor: "#feb2b2" } },
  focus_bg_red_400: { "&:focus": { backgroundColor: "#fc8181" } },
  focus_bg_red_500: { "&:focus": { backgroundColor: "#f56565" } },
  focus_bg_red_600: { "&:focus": { backgroundColor: "#e53e3e" } },
  focus_bg_red_700: { "&:focus": { backgroundColor: "#c53030" } },
  focus_bg_red_800: { "&:focus": { backgroundColor: "#9b2c2c" } },
  focus_bg_red_900: { "&:focus": { backgroundColor: "#742a2a" } },
  focus_bg_teal_100: { "&:focus": { backgroundColor: "#e6fffa" } },
  focus_bg_teal_200: { "&:focus": { backgroundColor: "#b2f5ea" } },
  focus_bg_teal_300: { "&:focus": { backgroundColor: "#81e6d9" } },
  focus_bg_teal_400: { "&:focus": { backgroundColor: "#4fd1c5" } },
  focus_bg_teal_500: { "&:focus": { backgroundColor: "#38b2ac" } },
  focus_bg_teal_600: { "&:focus": { backgroundColor: "#319795" } },
  focus_bg_teal_700: { "&:focus": { backgroundColor: "#2c7a7b" } },
  focus_bg_teal_800: { "&:focus": { backgroundColor: "#285e61" } },
  focus_bg_teal_900: { "&:focus": { backgroundColor: "#234e52" } },
  focus_bg_transparent: { "&:focus": { backgroundColor: "transparent" } },
  focus_bg_white: { "&:focus": { backgroundColor: "#fff" } },
  focus_bg_yellow_100: { "&:focus": { backgroundColor: "#fffff0" } },
  focus_bg_yellow_200: { "&:focus": { backgroundColor: "#fefcbf" } },
  focus_bg_yellow_300: { "&:focus": { backgroundColor: "#faf089" } },
  focus_bg_yellow_400: { "&:focus": { backgroundColor: "#f6e05e" } },
  focus_bg_yellow_500: { "&:focus": { backgroundColor: "#ecc94b" } },
  focus_bg_yellow_600: { "&:focus": { backgroundColor: "#d69e2e" } },
  focus_bg_yellow_700: { "&:focus": { backgroundColor: "#b7791f" } },
  focus_bg_yellow_800: { "&:focus": { backgroundColor: "#975a16" } },
  focus_bg_yellow_900: { "&:focus": { backgroundColor: "#744210" } },
  focus_border_black: { "&:focus": { borderColor: "#000" } },
  focus_border_blue_100: { "&:focus": { borderColor: "#ebf8ff" } },
  focus_border_blue_200: { "&:focus": { borderColor: "#bee3f8" } },
  focus_border_blue_300: { "&:focus": { borderColor: "#90cdf4" } },
  focus_border_blue_400: { "&:focus": { borderColor: "#63b3ed" } },
  focus_border_blue_500: { "&:focus": { borderColor: "#4299e1" } },
  focus_border_blue_600: { "&:focus": { borderColor: "#3182ce" } },
  focus_border_blue_700: { "&:focus": { borderColor: "#2b6cb0" } },
  focus_border_blue_800: { "&:focus": { borderColor: "#2c5282" } },
  focus_border_blue_900: { "&:focus": { borderColor: "#2a4365" } },
  focus_border_gray_100: { "&:focus": { borderColor: "#f7fafc" } },
  focus_border_gray_200: { "&:focus": { borderColor: "#edf2f7" } },
  focus_border_gray_300: { "&:focus": { borderColor: "#e2e8f0" } },
  focus_border_gray_400: { "&:focus": { borderColor: "#cbd5e0" } },
  focus_border_gray_500: { "&:focus": { borderColor: "#a0aec0" } },
  focus_border_gray_600: { "&:focus": { borderColor: "#718096" } },
  focus_border_gray_700: { "&:focus": { borderColor: "#4a5568" } },
  focus_border_gray_800: { "&:focus": { borderColor: "#2d3748" } },
  focus_border_gray_900: { "&:focus": { borderColor: "#1a202c" } },
  focus_border_green_100: { "&:focus": { borderColor: "#f0fff4" } },
  focus_border_green_200: { "&:focus": { borderColor: "#c6f6d5" } },
  focus_border_green_300: { "&:focus": { borderColor: "#9ae6b4" } },
  focus_border_green_400: { "&:focus": { borderColor: "#68d391" } },
  focus_border_green_500: { "&:focus": { borderColor: "#48bb78" } },
  focus_border_green_600: { "&:focus": { borderColor: "#38a169" } },
  focus_border_green_700: { "&:focus": { borderColor: "#2f855a" } },
  focus_border_green_800: { "&:focus": { borderColor: "#276749" } },
  focus_border_green_900: { "&:focus": { borderColor: "#22543d" } },
  focus_border_indigo_100: { "&:focus": { borderColor: "#ebf4ff" } },
  focus_border_indigo_200: { "&:focus": { borderColor: "#c3dafe" } },
  focus_border_indigo_300: { "&:focus": { borderColor: "#a3bffa" } },
  focus_border_indigo_400: { "&:focus": { borderColor: "#7f9cf5" } },
  focus_border_indigo_500: { "&:focus": { borderColor: "#667eea" } },
  focus_border_indigo_600: { "&:focus": { borderColor: "#5a67d8" } },
  focus_border_indigo_700: { "&:focus": { borderColor: "#4c51bf" } },
  focus_border_indigo_800: { "&:focus": { borderColor: "#434190" } },
  focus_border_indigo_900: { "&:focus": { borderColor: "#3c366b" } },
  focus_border_orange_100: { "&:focus": { borderColor: "#fffaf0" } },
  focus_border_orange_200: { "&:focus": { borderColor: "#feebc8" } },
  focus_border_orange_300: { "&:focus": { borderColor: "#fbd38d" } },
  focus_border_orange_400: { "&:focus": { borderColor: "#f6ad55" } },
  focus_border_orange_500: { "&:focus": { borderColor: "#ed8936" } },
  focus_border_orange_600: { "&:focus": { borderColor: "#dd6b20" } },
  focus_border_orange_700: { "&:focus": { borderColor: "#c05621" } },
  focus_border_orange_800: { "&:focus": { borderColor: "#9c4221" } },
  focus_border_orange_900: { "&:focus": { borderColor: "#7b341e" } },
  focus_border_pink_100: { "&:focus": { borderColor: "#fff5f7" } },
  focus_border_pink_200: { "&:focus": { borderColor: "#fed7e2" } },
  focus_border_pink_300: { "&:focus": { borderColor: "#fbb6ce" } },
  focus_border_pink_400: { "&:focus": { borderColor: "#f687b3" } },
  focus_border_pink_500: { "&:focus": { borderColor: "#ed64a6" } },
  focus_border_pink_600: { "&:focus": { borderColor: "#d53f8c" } },
  focus_border_pink_700: { "&:focus": { borderColor: "#b83280" } },
  focus_border_pink_800: { "&:focus": { borderColor: "#97266d" } },
  focus_border_pink_900: { "&:focus": { borderColor: "#702459" } },
  focus_border_purple_100: { "&:focus": { borderColor: "#faf5ff" } },
  focus_border_purple_200: { "&:focus": { borderColor: "#e9d8fd" } },
  focus_border_purple_300: { "&:focus": { borderColor: "#d6bcfa" } },
  focus_border_purple_400: { "&:focus": { borderColor: "#b794f4" } },
  focus_border_purple_500: { "&:focus": { borderColor: "#9f7aea" } },
  focus_border_purple_600: { "&:focus": { borderColor: "#805ad5" } },
  focus_border_purple_700: { "&:focus": { borderColor: "#6b46c1" } },
  focus_border_purple_800: { "&:focus": { borderColor: "#553c9a" } },
  focus_border_purple_900: { "&:focus": { borderColor: "#44337a" } },
  focus_border_red_100: { "&:focus": { borderColor: "#fff5f5" } },
  focus_border_red_200: { "&:focus": { borderColor: "#fed7d7" } },
  focus_border_red_300: { "&:focus": { borderColor: "#feb2b2" } },
  focus_border_red_400: { "&:focus": { borderColor: "#fc8181" } },
  focus_border_red_500: { "&:focus": { borderColor: "#f56565" } },
  focus_border_red_600: { "&:focus": { borderColor: "#e53e3e" } },
  focus_border_red_700: { "&:focus": { borderColor: "#c53030" } },
  focus_border_red_800: { "&:focus": { borderColor: "#9b2c2c" } },
  focus_border_red_900: { "&:focus": { borderColor: "#742a2a" } },
  focus_border_teal_100: { "&:focus": { borderColor: "#e6fffa" } },
  focus_border_teal_200: { "&:focus": { borderColor: "#b2f5ea" } },
  focus_border_teal_300: { "&:focus": { borderColor: "#81e6d9" } },
  focus_border_teal_400: { "&:focus": { borderColor: "#4fd1c5" } },
  focus_border_teal_500: { "&:focus": { borderColor: "#38b2ac" } },
  focus_border_teal_600: { "&:focus": { borderColor: "#319795" } },
  focus_border_teal_700: { "&:focus": { borderColor: "#2c7a7b" } },
  focus_border_teal_800: { "&:focus": { borderColor: "#285e61" } },
  focus_border_teal_900: { "&:focus": { borderColor: "#234e52" } },
  focus_border_transparent: { "&:focus": { borderColor: "transparent" } },
  focus_border_white: { "&:focus": { borderColor: "#fff" } },
  focus_border_yellow_100: { "&:focus": { borderColor: "#fffff0" } },
  focus_border_yellow_200: { "&:focus": { borderColor: "#fefcbf" } },
  focus_border_yellow_300: { "&:focus": { borderColor: "#faf089" } },
  focus_border_yellow_400: { "&:focus": { borderColor: "#f6e05e" } },
  focus_border_yellow_500: { "&:focus": { borderColor: "#ecc94b" } },
  focus_border_yellow_600: { "&:focus": { borderColor: "#d69e2e" } },
  focus_border_yellow_700: { "&:focus": { borderColor: "#b7791f" } },
  focus_border_yellow_800: { "&:focus": { borderColor: "#975a16" } },
  focus_border_yellow_900: { "&:focus": { borderColor: "#744210" } },
  focus_font_black: { "&:focus": { fontWeight: "900" } },
  focus_font_bold: { "&:focus": { fontWeight: "700" } },
  focus_font_extrabold: { "&:focus": { fontWeight: "800" } },
  focus_font_hairline: { "&:focus": { fontWeight: "100" } },
  focus_font_light: { "&:focus": { fontWeight: "300" } },
  focus_font_medium: { "&:focus": { fontWeight: "500" } },
  focus_font_normal: { "&:focus": { fontWeight: "400" } },
  focus_font_semibold: { "&:focus": { fontWeight: "600" } },
  focus_font_thin: { "&:focus": { fontWeight: "200" } },
  focus_line_through: { "&:focus": { textDecoration: "line-through" } },
  focus_no_underline: { "&:focus": { textDecoration: "none" } },
  focus_not_sr_only: {
    "&:focus": {
      position: "static",
      width: "auto",
      height: "auto",
      padding: "0",
      margin: "0",
      overflow: "visible",
      clip: "auto",
      whiteSpace: "normal"
    }
  },
  focus_opacity_0: { "&:focus": { opacity: "0" } },
  focus_opacity_100: { "&:focus": { opacity: "1" } },
  focus_opacity_25: { "&:focus": { opacity: "0.25" } },
  focus_opacity_50: { "&:focus": { opacity: "0.5" } },
  focus_opacity_75: { "&:focus": { opacity: "0.75" } },
  focus_outline_none: { "&:focus": { outline: "0" } },
  focus_shadow: {
    "&:focus": {
      boxShadow:
        "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)"
    }
  },
  focus_shadow_2xl: {
    "&:focus": { boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.25)" }
  },
  focus_shadow_inner: {
    "&:focus": { boxShadow: "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)" }
  },
  focus_shadow_lg: {
    "&:focus": {
      boxShadow:
        "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)"
    }
  },
  focus_shadow_md: {
    "&:focus": {
      boxShadow:
        "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)"
    }
  },
  focus_shadow_none: { "&:focus": { boxShadow: "none" } },
  focus_shadow_outline: {
    "&:focus": { boxShadow: "0 0 0 3px rgba(66, 153, 225, 0.5)" }
  },
  focus_shadow_xl: {
    "&:focus": {
      boxShadow:
        "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)"
    }
  },
  focus_sr_only: {
    "&:focus": {
      position: "absolute",
      width: "1px",
      height: "1px",
      padding: "0",
      margin: "-1px",
      overflow: "hidden",
      clip: "rect(0, 0, 0, 0)",
      whiteSpace: "nowrap",
      borderWidth: "0"
    }
  },
  focus_text_black: { "&:focus": { color: "#000" } },
  focus_text_blue_100: { "&:focus": { color: "#ebf8ff" } },
  focus_text_blue_200: { "&:focus": { color: "#bee3f8" } },
  focus_text_blue_300: { "&:focus": { color: "#90cdf4" } },
  focus_text_blue_400: { "&:focus": { color: "#63b3ed" } },
  focus_text_blue_500: { "&:focus": { color: "#4299e1" } },
  focus_text_blue_600: { "&:focus": { color: "#3182ce" } },
  focus_text_blue_700: { "&:focus": { color: "#2b6cb0" } },
  focus_text_blue_800: { "&:focus": { color: "#2c5282" } },
  focus_text_blue_900: { "&:focus": { color: "#2a4365" } },
  focus_text_gray_100: { "&:focus": { color: "#f7fafc" } },
  focus_text_gray_200: { "&:focus": { color: "#edf2f7" } },
  focus_text_gray_300: { "&:focus": { color: "#e2e8f0" } },
  focus_text_gray_400: { "&:focus": { color: "#cbd5e0" } },
  focus_text_gray_500: { "&:focus": { color: "#a0aec0" } },
  focus_text_gray_600: { "&:focus": { color: "#718096" } },
  focus_text_gray_700: { "&:focus": { color: "#4a5568" } },
  focus_text_gray_800: { "&:focus": { color: "#2d3748" } },
  focus_text_gray_900: { "&:focus": { color: "#1a202c" } },
  focus_text_green_100: { "&:focus": { color: "#f0fff4" } },
  focus_text_green_200: { "&:focus": { color: "#c6f6d5" } },
  focus_text_green_300: { "&:focus": { color: "#9ae6b4" } },
  focus_text_green_400: { "&:focus": { color: "#68d391" } },
  focus_text_green_500: { "&:focus": { color: "#48bb78" } },
  focus_text_green_600: { "&:focus": { color: "#38a169" } },
  focus_text_green_700: { "&:focus": { color: "#2f855a" } },
  focus_text_green_800: { "&:focus": { color: "#276749" } },
  focus_text_green_900: { "&:focus": { color: "#22543d" } },
  focus_text_indigo_100: { "&:focus": { color: "#ebf4ff" } },
  focus_text_indigo_200: { "&:focus": { color: "#c3dafe" } },
  focus_text_indigo_300: { "&:focus": { color: "#a3bffa" } },
  focus_text_indigo_400: { "&:focus": { color: "#7f9cf5" } },
  focus_text_indigo_500: { "&:focus": { color: "#667eea" } },
  focus_text_indigo_600: { "&:focus": { color: "#5a67d8" } },
  focus_text_indigo_700: { "&:focus": { color: "#4c51bf" } },
  focus_text_indigo_800: { "&:focus": { color: "#434190" } },
  focus_text_indigo_900: { "&:focus": { color: "#3c366b" } },
  focus_text_orange_100: { "&:focus": { color: "#fffaf0" } },
  focus_text_orange_200: { "&:focus": { color: "#feebc8" } },
  focus_text_orange_300: { "&:focus": { color: "#fbd38d" } },
  focus_text_orange_400: { "&:focus": { color: "#f6ad55" } },
  focus_text_orange_500: { "&:focus": { color: "#ed8936" } },
  focus_text_orange_600: { "&:focus": { color: "#dd6b20" } },
  focus_text_orange_700: { "&:focus": { color: "#c05621" } },
  focus_text_orange_800: { "&:focus": { color: "#9c4221" } },
  focus_text_orange_900: { "&:focus": { color: "#7b341e" } },
  focus_text_pink_100: { "&:focus": { color: "#fff5f7" } },
  focus_text_pink_200: { "&:focus": { color: "#fed7e2" } },
  focus_text_pink_300: { "&:focus": { color: "#fbb6ce" } },
  focus_text_pink_400: { "&:focus": { color: "#f687b3" } },
  focus_text_pink_500: { "&:focus": { color: "#ed64a6" } },
  focus_text_pink_600: { "&:focus": { color: "#d53f8c" } },
  focus_text_pink_700: { "&:focus": { color: "#b83280" } },
  focus_text_pink_800: { "&:focus": { color: "#97266d" } },
  focus_text_pink_900: { "&:focus": { color: "#702459" } },
  focus_text_purple_100: { "&:focus": { color: "#faf5ff" } },
  focus_text_purple_200: { "&:focus": { color: "#e9d8fd" } },
  focus_text_purple_300: { "&:focus": { color: "#d6bcfa" } },
  focus_text_purple_400: { "&:focus": { color: "#b794f4" } },
  focus_text_purple_500: { "&:focus": { color: "#9f7aea" } },
  focus_text_purple_600: { "&:focus": { color: "#805ad5" } },
  focus_text_purple_700: { "&:focus": { color: "#6b46c1" } },
  focus_text_purple_800: { "&:focus": { color: "#553c9a" } },
  focus_text_purple_900: { "&:focus": { color: "#44337a" } },
  focus_text_red_100: { "&:focus": { color: "#fff5f5" } },
  focus_text_red_200: { "&:focus": { color: "#fed7d7" } },
  focus_text_red_300: { "&:focus": { color: "#feb2b2" } },
  focus_text_red_400: { "&:focus": { color: "#fc8181" } },
  focus_text_red_500: { "&:focus": { color: "#f56565" } },
  focus_text_red_600: { "&:focus": { color: "#e53e3e" } },
  focus_text_red_700: { "&:focus": { color: "#c53030" } },
  focus_text_red_800: { "&:focus": { color: "#9b2c2c" } },
  focus_text_red_900: { "&:focus": { color: "#742a2a" } },
  focus_text_teal_100: { "&:focus": { color: "#e6fffa" } },
  focus_text_teal_200: { "&:focus": { color: "#b2f5ea" } },
  focus_text_teal_300: { "&:focus": { color: "#81e6d9" } },
  focus_text_teal_400: { "&:focus": { color: "#4fd1c5" } },
  focus_text_teal_500: { "&:focus": { color: "#38b2ac" } },
  focus_text_teal_600: { "&:focus": { color: "#319795" } },
  focus_text_teal_700: { "&:focus": { color: "#2c7a7b" } },
  focus_text_teal_800: { "&:focus": { color: "#285e61" } },
  focus_text_teal_900: { "&:focus": { color: "#234e52" } },
  focus_text_transparent: { "&:focus": { color: "transparent" } },
  focus_text_white: { "&:focus": { color: "#fff" } },
  focus_text_yellow_100: { "&:focus": { color: "#fffff0" } },
  focus_text_yellow_200: { "&:focus": { color: "#fefcbf" } },
  focus_text_yellow_300: { "&:focus": { color: "#faf089" } },
  focus_text_yellow_400: { "&:focus": { color: "#f6e05e" } },
  focus_text_yellow_500: { "&:focus": { color: "#ecc94b" } },
  focus_text_yellow_600: { "&:focus": { color: "#d69e2e" } },
  focus_text_yellow_700: { "&:focus": { color: "#b7791f" } },
  focus_text_yellow_800: { "&:focus": { color: "#975a16" } },
  focus_text_yellow_900: { "&:focus": { color: "#744210" } },
  focus_underline: { "&:focus": { textDecoration: "underline" } },
  font_black: { fontWeight: "900" },
  font_bold: { fontWeight: "700" },
  font_extrabold: { fontWeight: "800" },
  font_hairline: { fontWeight: "100" },
  font_light: { fontWeight: "300" },
  font_medium: { fontWeight: "500" },
  font_mono: {
    fontFamily:
      'Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace'
  },
  font_normal: { fontWeight: "400" },
  font_sans: {
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"'
  },
  font_semibold: { fontWeight: "600" },
  font_serif: {
    fontFamily: 'Georgia, Cambria, "Times New Roman", Times, serif'
  },
  font_thin: { fontWeight: "200" },
  h_0: { height: "0" },
  h_1: { height: "0.25rem" },
  h_10: { height: "2.5rem" },
  h_12: { height: "3rem" },
  h_16: { height: "4rem" },
  h_2: { height: "0.5rem" },
  h_20: { height: "5rem" },
  h_24: { height: "6rem" },
  h_3: { height: "0.75rem" },
  h_32: { height: "8rem" },
  h_4: { height: "1rem" },
  h_40: { height: "10rem" },
  h_48: { height: "12rem" },
  h_5: { height: "1.25rem" },
  h_56: { height: "14rem" },
  h_6: { height: "1.5rem" },
  h_64: { height: "16rem" },
  h_8: { height: "2rem" },
  h_auto: { height: "auto" },
  h_full: { height: "100%" },
  h_px: { height: "1px" },
  h_screen: { height: "100vh" },
  hidden: { display: "none" },
  hover_bg_black: { "&:hover": { backgroundColor: "#000" } },
  hover_bg_blue_100: { "&:hover": { backgroundColor: "#ebf8ff" } },
  hover_bg_blue_200: { "&:hover": { backgroundColor: "#bee3f8" } },
  hover_bg_blue_300: { "&:hover": { backgroundColor: "#90cdf4" } },
  hover_bg_blue_400: { "&:hover": { backgroundColor: "#63b3ed" } },
  hover_bg_blue_500: { "&:hover": { backgroundColor: "#4299e1" } },
  hover_bg_blue_600: { "&:hover": { backgroundColor: "#3182ce" } },
  hover_bg_blue_700: { "&:hover": { backgroundColor: "#2b6cb0" } },
  hover_bg_blue_800: { "&:hover": { backgroundColor: "#2c5282" } },
  hover_bg_blue_900: { "&:hover": { backgroundColor: "#2a4365" } },
  hover_bg_gray_100: { "&:hover": { backgroundColor: "#f7fafc" } },
  hover_bg_gray_200: { "&:hover": { backgroundColor: "#edf2f7" } },
  hover_bg_gray_300: { "&:hover": { backgroundColor: "#e2e8f0" } },
  hover_bg_gray_400: { "&:hover": { backgroundColor: "#cbd5e0" } },
  hover_bg_gray_500: { "&:hover": { backgroundColor: "#a0aec0" } },
  hover_bg_gray_600: { "&:hover": { backgroundColor: "#718096" } },
  hover_bg_gray_700: { "&:hover": { backgroundColor: "#4a5568" } },
  hover_bg_gray_800: { "&:hover": { backgroundColor: "#2d3748" } },
  hover_bg_gray_900: { "&:hover": { backgroundColor: "#1a202c" } },
  hover_bg_green_100: { "&:hover": { backgroundColor: "#f0fff4" } },
  hover_bg_green_200: { "&:hover": { backgroundColor: "#c6f6d5" } },
  hover_bg_green_300: { "&:hover": { backgroundColor: "#9ae6b4" } },
  hover_bg_green_400: { "&:hover": { backgroundColor: "#68d391" } },
  hover_bg_green_500: { "&:hover": { backgroundColor: "#48bb78" } },
  hover_bg_green_600: { "&:hover": { backgroundColor: "#38a169" } },
  hover_bg_green_700: { "&:hover": { backgroundColor: "#2f855a" } },
  hover_bg_green_800: { "&:hover": { backgroundColor: "#276749" } },
  hover_bg_green_900: { "&:hover": { backgroundColor: "#22543d" } },
  hover_bg_indigo_100: { "&:hover": { backgroundColor: "#ebf4ff" } },
  hover_bg_indigo_200: { "&:hover": { backgroundColor: "#c3dafe" } },
  hover_bg_indigo_300: { "&:hover": { backgroundColor: "#a3bffa" } },
  hover_bg_indigo_400: { "&:hover": { backgroundColor: "#7f9cf5" } },
  hover_bg_indigo_500: { "&:hover": { backgroundColor: "#667eea" } },
  hover_bg_indigo_600: { "&:hover": { backgroundColor: "#5a67d8" } },
  hover_bg_indigo_700: { "&:hover": { backgroundColor: "#4c51bf" } },
  hover_bg_indigo_800: { "&:hover": { backgroundColor: "#434190" } },
  hover_bg_indigo_900: { "&:hover": { backgroundColor: "#3c366b" } },
  hover_bg_orange_100: { "&:hover": { backgroundColor: "#fffaf0" } },
  hover_bg_orange_200: { "&:hover": { backgroundColor: "#feebc8" } },
  hover_bg_orange_300: { "&:hover": { backgroundColor: "#fbd38d" } },
  hover_bg_orange_400: { "&:hover": { backgroundColor: "#f6ad55" } },
  hover_bg_orange_500: { "&:hover": { backgroundColor: "#ed8936" } },
  hover_bg_orange_600: { "&:hover": { backgroundColor: "#dd6b20" } },
  hover_bg_orange_700: { "&:hover": { backgroundColor: "#c05621" } },
  hover_bg_orange_800: { "&:hover": { backgroundColor: "#9c4221" } },
  hover_bg_orange_900: { "&:hover": { backgroundColor: "#7b341e" } },
  hover_bg_pink_100: { "&:hover": { backgroundColor: "#fff5f7" } },
  hover_bg_pink_200: { "&:hover": { backgroundColor: "#fed7e2" } },
  hover_bg_pink_300: { "&:hover": { backgroundColor: "#fbb6ce" } },
  hover_bg_pink_400: { "&:hover": { backgroundColor: "#f687b3" } },
  hover_bg_pink_500: { "&:hover": { backgroundColor: "#ed64a6" } },
  hover_bg_pink_600: { "&:hover": { backgroundColor: "#d53f8c" } },
  hover_bg_pink_700: { "&:hover": { backgroundColor: "#b83280" } },
  hover_bg_pink_800: { "&:hover": { backgroundColor: "#97266d" } },
  hover_bg_pink_900: { "&:hover": { backgroundColor: "#702459" } },
  hover_bg_purple_100: { "&:hover": { backgroundColor: "#faf5ff" } },
  hover_bg_purple_200: { "&:hover": { backgroundColor: "#e9d8fd" } },
  hover_bg_purple_300: { "&:hover": { backgroundColor: "#d6bcfa" } },
  hover_bg_purple_400: { "&:hover": { backgroundColor: "#b794f4" } },
  hover_bg_purple_500: { "&:hover": { backgroundColor: "#9f7aea" } },
  hover_bg_purple_600: { "&:hover": { backgroundColor: "#805ad5" } },
  hover_bg_purple_700: { "&:hover": { backgroundColor: "#6b46c1" } },
  hover_bg_purple_800: { "&:hover": { backgroundColor: "#553c9a" } },
  hover_bg_purple_900: { "&:hover": { backgroundColor: "#44337a" } },
  hover_bg_red_100: { "&:hover": { backgroundColor: "#fff5f5" } },
  hover_bg_red_200: { "&:hover": { backgroundColor: "#fed7d7" } },
  hover_bg_red_300: { "&:hover": { backgroundColor: "#feb2b2" } },
  hover_bg_red_400: { "&:hover": { backgroundColor: "#fc8181" } },
  hover_bg_red_500: { "&:hover": { backgroundColor: "#f56565" } },
  hover_bg_red_600: { "&:hover": { backgroundColor: "#e53e3e" } },
  hover_bg_red_700: { "&:hover": { backgroundColor: "#c53030" } },
  hover_bg_red_800: { "&:hover": { backgroundColor: "#9b2c2c" } },
  hover_bg_red_900: { "&:hover": { backgroundColor: "#742a2a" } },
  hover_bg_teal_100: { "&:hover": { backgroundColor: "#e6fffa" } },
  hover_bg_teal_200: { "&:hover": { backgroundColor: "#b2f5ea" } },
  hover_bg_teal_300: { "&:hover": { backgroundColor: "#81e6d9" } },
  hover_bg_teal_400: { "&:hover": { backgroundColor: "#4fd1c5" } },
  hover_bg_teal_500: { "&:hover": { backgroundColor: "#38b2ac" } },
  hover_bg_teal_600: { "&:hover": { backgroundColor: "#319795" } },
  hover_bg_teal_700: { "&:hover": { backgroundColor: "#2c7a7b" } },
  hover_bg_teal_800: { "&:hover": { backgroundColor: "#285e61" } },
  hover_bg_teal_900: { "&:hover": { backgroundColor: "#234e52" } },
  hover_bg_transparent: { "&:hover": { backgroundColor: "transparent" } },
  hover_bg_white: { "&:hover": { backgroundColor: "#fff" } },
  hover_bg_yellow_100: { "&:hover": { backgroundColor: "#fffff0" } },
  hover_bg_yellow_200: { "&:hover": { backgroundColor: "#fefcbf" } },
  hover_bg_yellow_300: { "&:hover": { backgroundColor: "#faf089" } },
  hover_bg_yellow_400: { "&:hover": { backgroundColor: "#f6e05e" } },
  hover_bg_yellow_500: { "&:hover": { backgroundColor: "#ecc94b" } },
  hover_bg_yellow_600: { "&:hover": { backgroundColor: "#d69e2e" } },
  hover_bg_yellow_700: { "&:hover": { backgroundColor: "#b7791f" } },
  hover_bg_yellow_800: { "&:hover": { backgroundColor: "#975a16" } },
  hover_bg_yellow_900: { "&:hover": { backgroundColor: "#744210" } },
  hover_border_black: { "&:hover": { borderColor: "#000" } },
  hover_border_blue_100: { "&:hover": { borderColor: "#ebf8ff" } },
  hover_border_blue_200: { "&:hover": { borderColor: "#bee3f8" } },
  hover_border_blue_300: { "&:hover": { borderColor: "#90cdf4" } },
  hover_border_blue_400: { "&:hover": { borderColor: "#63b3ed" } },
  hover_border_blue_500: { "&:hover": { borderColor: "#4299e1" } },
  hover_border_blue_600: { "&:hover": { borderColor: "#3182ce" } },
  hover_border_blue_700: { "&:hover": { borderColor: "#2b6cb0" } },
  hover_border_blue_800: { "&:hover": { borderColor: "#2c5282" } },
  hover_border_blue_900: { "&:hover": { borderColor: "#2a4365" } },
  hover_border_gray_100: { "&:hover": { borderColor: "#f7fafc" } },
  hover_border_gray_200: { "&:hover": { borderColor: "#edf2f7" } },
  hover_border_gray_300: { "&:hover": { borderColor: "#e2e8f0" } },
  hover_border_gray_400: { "&:hover": { borderColor: "#cbd5e0" } },
  hover_border_gray_500: { "&:hover": { borderColor: "#a0aec0" } },
  hover_border_gray_600: { "&:hover": { borderColor: "#718096" } },
  hover_border_gray_700: { "&:hover": { borderColor: "#4a5568" } },
  hover_border_gray_800: { "&:hover": { borderColor: "#2d3748" } },
  hover_border_gray_900: { "&:hover": { borderColor: "#1a202c" } },
  hover_border_green_100: { "&:hover": { borderColor: "#f0fff4" } },
  hover_border_green_200: { "&:hover": { borderColor: "#c6f6d5" } },
  hover_border_green_300: { "&:hover": { borderColor: "#9ae6b4" } },
  hover_border_green_400: { "&:hover": { borderColor: "#68d391" } },
  hover_border_green_500: { "&:hover": { borderColor: "#48bb78" } },
  hover_border_green_600: { "&:hover": { borderColor: "#38a169" } },
  hover_border_green_700: { "&:hover": { borderColor: "#2f855a" } },
  hover_border_green_800: { "&:hover": { borderColor: "#276749" } },
  hover_border_green_900: { "&:hover": { borderColor: "#22543d" } },
  hover_border_indigo_100: { "&:hover": { borderColor: "#ebf4ff" } },
  hover_border_indigo_200: { "&:hover": { borderColor: "#c3dafe" } },
  hover_border_indigo_300: { "&:hover": { borderColor: "#a3bffa" } },
  hover_border_indigo_400: { "&:hover": { borderColor: "#7f9cf5" } },
  hover_border_indigo_500: { "&:hover": { borderColor: "#667eea" } },
  hover_border_indigo_600: { "&:hover": { borderColor: "#5a67d8" } },
  hover_border_indigo_700: { "&:hover": { borderColor: "#4c51bf" } },
  hover_border_indigo_800: { "&:hover": { borderColor: "#434190" } },
  hover_border_indigo_900: { "&:hover": { borderColor: "#3c366b" } },
  hover_border_orange_100: { "&:hover": { borderColor: "#fffaf0" } },
  hover_border_orange_200: { "&:hover": { borderColor: "#feebc8" } },
  hover_border_orange_300: { "&:hover": { borderColor: "#fbd38d" } },
  hover_border_orange_400: { "&:hover": { borderColor: "#f6ad55" } },
  hover_border_orange_500: { "&:hover": { borderColor: "#ed8936" } },
  hover_border_orange_600: { "&:hover": { borderColor: "#dd6b20" } },
  hover_border_orange_700: { "&:hover": { borderColor: "#c05621" } },
  hover_border_orange_800: { "&:hover": { borderColor: "#9c4221" } },
  hover_border_orange_900: { "&:hover": { borderColor: "#7b341e" } },
  hover_border_pink_100: { "&:hover": { borderColor: "#fff5f7" } },
  hover_border_pink_200: { "&:hover": { borderColor: "#fed7e2" } },
  hover_border_pink_300: { "&:hover": { borderColor: "#fbb6ce" } },
  hover_border_pink_400: { "&:hover": { borderColor: "#f687b3" } },
  hover_border_pink_500: { "&:hover": { borderColor: "#ed64a6" } },
  hover_border_pink_600: { "&:hover": { borderColor: "#d53f8c" } },
  hover_border_pink_700: { "&:hover": { borderColor: "#b83280" } },
  hover_border_pink_800: { "&:hover": { borderColor: "#97266d" } },
  hover_border_pink_900: { "&:hover": { borderColor: "#702459" } },
  hover_border_purple_100: { "&:hover": { borderColor: "#faf5ff" } },
  hover_border_purple_200: { "&:hover": { borderColor: "#e9d8fd" } },
  hover_border_purple_300: { "&:hover": { borderColor: "#d6bcfa" } },
  hover_border_purple_400: { "&:hover": { borderColor: "#b794f4" } },
  hover_border_purple_500: { "&:hover": { borderColor: "#9f7aea" } },
  hover_border_purple_600: { "&:hover": { borderColor: "#805ad5" } },
  hover_border_purple_700: { "&:hover": { borderColor: "#6b46c1" } },
  hover_border_purple_800: { "&:hover": { borderColor: "#553c9a" } },
  hover_border_purple_900: { "&:hover": { borderColor: "#44337a" } },
  hover_border_red_100: { "&:hover": { borderColor: "#fff5f5" } },
  hover_border_red_200: { "&:hover": { borderColor: "#fed7d7" } },
  hover_border_red_300: { "&:hover": { borderColor: "#feb2b2" } },
  hover_border_red_400: { "&:hover": { borderColor: "#fc8181" } },
  hover_border_red_500: { "&:hover": { borderColor: "#f56565" } },
  hover_border_red_600: { "&:hover": { borderColor: "#e53e3e" } },
  hover_border_red_700: { "&:hover": { borderColor: "#c53030" } },
  hover_border_red_800: { "&:hover": { borderColor: "#9b2c2c" } },
  hover_border_red_900: { "&:hover": { borderColor: "#742a2a" } },
  hover_border_teal_100: { "&:hover": { borderColor: "#e6fffa" } },
  hover_border_teal_200: { "&:hover": { borderColor: "#b2f5ea" } },
  hover_border_teal_300: { "&:hover": { borderColor: "#81e6d9" } },
  hover_border_teal_400: { "&:hover": { borderColor: "#4fd1c5" } },
  hover_border_teal_500: { "&:hover": { borderColor: "#38b2ac" } },
  hover_border_teal_600: { "&:hover": { borderColor: "#319795" } },
  hover_border_teal_700: { "&:hover": { borderColor: "#2c7a7b" } },
  hover_border_teal_800: { "&:hover": { borderColor: "#285e61" } },
  hover_border_teal_900: { "&:hover": { borderColor: "#234e52" } },
  hover_border_transparent: { "&:hover": { borderColor: "transparent" } },
  hover_border_white: { "&:hover": { borderColor: "#fff" } },
  hover_border_yellow_100: { "&:hover": { borderColor: "#fffff0" } },
  hover_border_yellow_200: { "&:hover": { borderColor: "#fefcbf" } },
  hover_border_yellow_300: { "&:hover": { borderColor: "#faf089" } },
  hover_border_yellow_400: { "&:hover": { borderColor: "#f6e05e" } },
  hover_border_yellow_500: { "&:hover": { borderColor: "#ecc94b" } },
  hover_border_yellow_600: { "&:hover": { borderColor: "#d69e2e" } },
  hover_border_yellow_700: { "&:hover": { borderColor: "#b7791f" } },
  hover_border_yellow_800: { "&:hover": { borderColor: "#975a16" } },
  hover_border_yellow_900: { "&:hover": { borderColor: "#744210" } },
  hover_font_black: { "&:hover": { fontWeight: "900" } },
  hover_font_bold: { "&:hover": { fontWeight: "700" } },
  hover_font_extrabold: { "&:hover": { fontWeight: "800" } },
  hover_font_hairline: { "&:hover": { fontWeight: "100" } },
  hover_font_light: { "&:hover": { fontWeight: "300" } },
  hover_font_medium: { "&:hover": { fontWeight: "500" } },
  hover_font_normal: { "&:hover": { fontWeight: "400" } },
  hover_font_semibold: { "&:hover": { fontWeight: "600" } },
  hover_font_thin: { "&:hover": { fontWeight: "200" } },
  hover_line_through: { "&:hover": { textDecoration: "line-through" } },
  hover_no_underline: { "&:hover": { textDecoration: "none" } },
  hover_opacity_0: { "&:hover": { opacity: "0" } },
  hover_opacity_100: { "&:hover": { opacity: "1" } },
  hover_opacity_25: { "&:hover": { opacity: "0.25" } },
  hover_opacity_50: { "&:hover": { opacity: "0.5" } },
  hover_opacity_75: { "&:hover": { opacity: "0.75" } },
  hover_shadow: {
    "&:hover": {
      boxShadow:
        "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)"
    }
  },
  hover_shadow_2xl: {
    "&:hover": { boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.25)" }
  },
  hover_shadow_inner: {
    "&:hover": { boxShadow: "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)" }
  },
  hover_shadow_lg: {
    "&:hover": {
      boxShadow:
        "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)"
    }
  },
  hover_shadow_md: {
    "&:hover": {
      boxShadow:
        "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)"
    }
  },
  hover_shadow_none: { "&:hover": { boxShadow: "none" } },
  hover_shadow_outline: {
    "&:hover": { boxShadow: "0 0 0 3px rgba(66, 153, 225, 0.5)" }
  },
  hover_shadow_xl: {
    "&:hover": {
      boxShadow:
        "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)"
    }
  },
  hover_text_black: { "&:hover": { color: "#000" } },
  hover_text_blue_100: { "&:hover": { color: "#ebf8ff" } },
  hover_text_blue_200: { "&:hover": { color: "#bee3f8" } },
  hover_text_blue_300: { "&:hover": { color: "#90cdf4" } },
  hover_text_blue_400: { "&:hover": { color: "#63b3ed" } },
  hover_text_blue_500: { "&:hover": { color: "#4299e1" } },
  hover_text_blue_600: { "&:hover": { color: "#3182ce" } },
  hover_text_blue_700: { "&:hover": { color: "#2b6cb0" } },
  hover_text_blue_800: { "&:hover": { color: "#2c5282" } },
  hover_text_blue_900: { "&:hover": { color: "#2a4365" } },
  hover_text_gray_100: { "&:hover": { color: "#f7fafc" } },
  hover_text_gray_200: { "&:hover": { color: "#edf2f7" } },
  hover_text_gray_300: { "&:hover": { color: "#e2e8f0" } },
  hover_text_gray_400: { "&:hover": { color: "#cbd5e0" } },
  hover_text_gray_500: { "&:hover": { color: "#a0aec0" } },
  hover_text_gray_600: { "&:hover": { color: "#718096" } },
  hover_text_gray_700: { "&:hover": { color: "#4a5568" } },
  hover_text_gray_800: { "&:hover": { color: "#2d3748" } },
  hover_text_gray_900: { "&:hover": { color: "#1a202c" } },
  hover_text_green_100: { "&:hover": { color: "#f0fff4" } },
  hover_text_green_200: { "&:hover": { color: "#c6f6d5" } },
  hover_text_green_300: { "&:hover": { color: "#9ae6b4" } },
  hover_text_green_400: { "&:hover": { color: "#68d391" } },
  hover_text_green_500: { "&:hover": { color: "#48bb78" } },
  hover_text_green_600: { "&:hover": { color: "#38a169" } },
  hover_text_green_700: { "&:hover": { color: "#2f855a" } },
  hover_text_green_800: { "&:hover": { color: "#276749" } },
  hover_text_green_900: { "&:hover": { color: "#22543d" } },
  hover_text_indigo_100: { "&:hover": { color: "#ebf4ff" } },
  hover_text_indigo_200: { "&:hover": { color: "#c3dafe" } },
  hover_text_indigo_300: { "&:hover": { color: "#a3bffa" } },
  hover_text_indigo_400: { "&:hover": { color: "#7f9cf5" } },
  hover_text_indigo_500: { "&:hover": { color: "#667eea" } },
  hover_text_indigo_600: { "&:hover": { color: "#5a67d8" } },
  hover_text_indigo_700: { "&:hover": { color: "#4c51bf" } },
  hover_text_indigo_800: { "&:hover": { color: "#434190" } },
  hover_text_indigo_900: { "&:hover": { color: "#3c366b" } },
  hover_text_orange_100: { "&:hover": { color: "#fffaf0" } },
  hover_text_orange_200: { "&:hover": { color: "#feebc8" } },
  hover_text_orange_300: { "&:hover": { color: "#fbd38d" } },
  hover_text_orange_400: { "&:hover": { color: "#f6ad55" } },
  hover_text_orange_500: { "&:hover": { color: "#ed8936" } },
  hover_text_orange_600: { "&:hover": { color: "#dd6b20" } },
  hover_text_orange_700: { "&:hover": { color: "#c05621" } },
  hover_text_orange_800: { "&:hover": { color: "#9c4221" } },
  hover_text_orange_900: { "&:hover": { color: "#7b341e" } },
  hover_text_pink_100: { "&:hover": { color: "#fff5f7" } },
  hover_text_pink_200: { "&:hover": { color: "#fed7e2" } },
  hover_text_pink_300: { "&:hover": { color: "#fbb6ce" } },
  hover_text_pink_400: { "&:hover": { color: "#f687b3" } },
  hover_text_pink_500: { "&:hover": { color: "#ed64a6" } },
  hover_text_pink_600: { "&:hover": { color: "#d53f8c" } },
  hover_text_pink_700: { "&:hover": { color: "#b83280" } },
  hover_text_pink_800: { "&:hover": { color: "#97266d" } },
  hover_text_pink_900: { "&:hover": { color: "#702459" } },
  hover_text_purple_100: { "&:hover": { color: "#faf5ff" } },
  hover_text_purple_200: { "&:hover": { color: "#e9d8fd" } },
  hover_text_purple_300: { "&:hover": { color: "#d6bcfa" } },
  hover_text_purple_400: { "&:hover": { color: "#b794f4" } },
  hover_text_purple_500: { "&:hover": { color: "#9f7aea" } },
  hover_text_purple_600: { "&:hover": { color: "#805ad5" } },
  hover_text_purple_700: { "&:hover": { color: "#6b46c1" } },
  hover_text_purple_800: { "&:hover": { color: "#553c9a" } },
  hover_text_purple_900: { "&:hover": { color: "#44337a" } },
  hover_text_red_100: { "&:hover": { color: "#fff5f5" } },
  hover_text_red_200: { "&:hover": { color: "#fed7d7" } },
  hover_text_red_300: { "&:hover": { color: "#feb2b2" } },
  hover_text_red_400: { "&:hover": { color: "#fc8181" } },
  hover_text_red_500: { "&:hover": { color: "#f56565" } },
  hover_text_red_600: { "&:hover": { color: "#e53e3e" } },
  hover_text_red_700: { "&:hover": { color: "#c53030" } },
  hover_text_red_800: { "&:hover": { color: "#9b2c2c" } },
  hover_text_red_900: { "&:hover": { color: "#742a2a" } },
  hover_text_teal_100: { "&:hover": { color: "#e6fffa" } },
  hover_text_teal_200: { "&:hover": { color: "#b2f5ea" } },
  hover_text_teal_300: { "&:hover": { color: "#81e6d9" } },
  hover_text_teal_400: { "&:hover": { color: "#4fd1c5" } },
  hover_text_teal_500: { "&:hover": { color: "#38b2ac" } },
  hover_text_teal_600: { "&:hover": { color: "#319795" } },
  hover_text_teal_700: { "&:hover": { color: "#2c7a7b" } },
  hover_text_teal_800: { "&:hover": { color: "#285e61" } },
  hover_text_teal_900: { "&:hover": { color: "#234e52" } },
  hover_text_transparent: { "&:hover": { color: "transparent" } },
  hover_text_white: { "&:hover": { color: "#fff" } },
  hover_text_yellow_100: { "&:hover": { color: "#fffff0" } },
  hover_text_yellow_200: { "&:hover": { color: "#fefcbf" } },
  hover_text_yellow_300: { "&:hover": { color: "#faf089" } },
  hover_text_yellow_400: { "&:hover": { color: "#f6e05e" } },
  hover_text_yellow_500: { "&:hover": { color: "#ecc94b" } },
  hover_text_yellow_600: { "&:hover": { color: "#d69e2e" } },
  hover_text_yellow_700: { "&:hover": { color: "#b7791f" } },
  hover_text_yellow_800: { "&:hover": { color: "#975a16" } },
  hover_text_yellow_900: { "&:hover": { color: "#744210" } },
  hover_underline: { "&:hover": { textDecoration: "underline" } },
  inline: { display: "inline" },
  inline_block: { display: "inline-block" },
  inline_flex: { display: ["-webkit-inline-box", "inline-flex"] },
  inset_0: { top: "0", right: "0", bottom: "0", left: "0" },
  inset_auto: { top: "auto", right: "auto", bottom: "auto", left: "auto" },
  inset_x_0: { right: "0", left: "0" },
  inset_x_auto: { right: "auto", left: "auto" },
  inset_y_0: { top: "0", bottom: "0" },
  inset_y_auto: { top: "auto", bottom: "auto" },
  invisible: { visibility: "hidden" },
  italic: { fontStyle: "italic" },
  items_baseline: { WebkitBoxAlign: "baseline", alignItems: "baseline" },
  items_center: { WebkitBoxAlign: "center", alignItems: "center" },
  items_end: { WebkitBoxAlign: "end", alignItems: "flex-end" },
  items_start: { WebkitBoxAlign: "start", alignItems: "flex-start" },
  items_stretch: { WebkitBoxAlign: "stretch", alignItems: "stretch" },
  justify_around: { justifyContent: "space-around" },
  justify_between: {
    WebkitBoxPack: "justify",
    justifyContent: "space-between"
  },
  justify_center: { WebkitBoxPack: "center", justifyContent: "center" },
  justify_end: { WebkitBoxPack: "end", justifyContent: "flex-end" },
  justify_start: { WebkitBoxPack: "start", justifyContent: "flex-start" },
  leading_loose: { lineHeight: "2" },
  leading_none: { lineHeight: "1" },
  leading_normal: { lineHeight: "1.5" },
  leading_relaxed: { lineHeight: "1.625" },
  leading_snug: { lineHeight: "1.375" },
  leading_tight: { lineHeight: "1.25" },
  left_0: { left: "0" },
  left_auto: { left: "auto" },
  line_through: { textDecoration: "line-through" },
  list_decimal: { listStyleType: "decimal" },
  list_disc: { listStyleType: "disc" },
  list_inside: { listStylePosition: "inside" },
  list_none: { listStyleType: "none" },
  list_outside: { listStylePosition: "outside" },
  lowercase: { textTransform: "lowercase" },
  m_0: { margin: "0" },
  m_1: { margin: "0.25rem" },
  m_10: { margin: "2.5rem" },
  m_12: { margin: "3rem" },
  m_16: { margin: "4rem" },
  m_2: { margin: "0.5rem" },
  m_20: { margin: "5rem" },
  m_24: { margin: "6rem" },
  m_3: { margin: "0.75rem" },
  m_32: { margin: "8rem" },
  m_4: { margin: "1rem" },
  m_40: { margin: "10rem" },
  m_48: { margin: "12rem" },
  m_5: { margin: "1.25rem" },
  m_56: { margin: "14rem" },
  m_6: { margin: "1.5rem" },
  m_64: { margin: "16rem" },
  m_8: { margin: "2rem" },
  m_auto: { margin: "auto" },
  m_px: { margin: "1px" },
  max_h_full: { maxHeight: "100%" },
  max_h_screen: { maxHeight: "100vh" },
  max_w_2xl: { maxWidth: "42rem" },
  max_w_3xl: { maxWidth: "48rem" },
  max_w_4xl: { maxWidth: "56rem" },
  max_w_5xl: { maxWidth: "64rem" },
  max_w_6xl: { maxWidth: "72rem" },
  max_w_full: { maxWidth: "100%" },
  max_w_lg: { maxWidth: "32rem" },
  max_w_md: { maxWidth: "28rem" },
  max_w_sm: { maxWidth: "24rem" },
  max_w_xl: { maxWidth: "36rem" },
  max_w_xs: { maxWidth: "20rem" },
  mb_0: { marginBottom: "0" },
  mb_1: { marginBottom: "0.25rem" },
  mb_10: { marginBottom: "2.5rem" },
  mb_12: { marginBottom: "3rem" },
  mb_16: { marginBottom: "4rem" },
  mb_2: { marginBottom: "0.5rem" },
  mb_20: { marginBottom: "5rem" },
  mb_24: { marginBottom: "6rem" },
  mb_3: { marginBottom: "0.75rem" },
  mb_32: { marginBottom: "8rem" },
  mb_4: { marginBottom: "1rem" },
  mb_40: { marginBottom: "10rem" },
  mb_48: { marginBottom: "12rem" },
  mb_5: { marginBottom: "1.25rem" },
  mb_56: { marginBottom: "14rem" },
  mb_6: { marginBottom: "1.5rem" },
  mb_64: { marginBottom: "16rem" },
  mb_8: { marginBottom: "2rem" },
  mb_auto: { marginBottom: "auto" },
  mb_px: { marginBottom: "1px" },
  min_h_0: { minHeight: "0" },
  min_h_full: { minHeight: "100%" },
  min_h_screen: { minHeight: "100vh" },
  min_w_0: { minWidth: "0" },
  min_w_full: { minWidth: "100%" },
  ml_0: { marginLeft: "0" },
  ml_1: { marginLeft: "0.25rem" },
  ml_10: { marginLeft: "2.5rem" },
  ml_12: { marginLeft: "3rem" },
  ml_16: { marginLeft: "4rem" },
  ml_2: { marginLeft: "0.5rem" },
  ml_20: { marginLeft: "5rem" },
  ml_24: { marginLeft: "6rem" },
  ml_3: { marginLeft: "0.75rem" },
  ml_32: { marginLeft: "8rem" },
  ml_4: { marginLeft: "1rem" },
  ml_40: { marginLeft: "10rem" },
  ml_48: { marginLeft: "12rem" },
  ml_5: { marginLeft: "1.25rem" },
  ml_56: { marginLeft: "14rem" },
  ml_6: { marginLeft: "1.5rem" },
  ml_64: { marginLeft: "16rem" },
  ml_8: { marginLeft: "2rem" },
  ml_auto: { marginLeft: "auto" },
  ml_px: { marginLeft: "1px" },
  mr_0: { marginRight: "0" },
  mr_1: { marginRight: "0.25rem" },
  mr_10: { marginRight: "2.5rem" },
  mr_12: { marginRight: "3rem" },
  mr_16: { marginRight: "4rem" },
  mr_2: { marginRight: "0.5rem" },
  mr_20: { marginRight: "5rem" },
  mr_24: { marginRight: "6rem" },
  mr_3: { marginRight: "0.75rem" },
  mr_32: { marginRight: "8rem" },
  mr_4: { marginRight: "1rem" },
  mr_40: { marginRight: "10rem" },
  mr_48: { marginRight: "12rem" },
  mr_5: { marginRight: "1.25rem" },
  mr_56: { marginRight: "14rem" },
  mr_6: { marginRight: "1.5rem" },
  mr_64: { marginRight: "16rem" },
  mr_8: { marginRight: "2rem" },
  mr_auto: { marginRight: "auto" },
  mr_px: { marginRight: "1px" },
  mt_0: { marginTop: "0" },
  mt_1: { marginTop: "0.25rem" },
  mt_10: { marginTop: "2.5rem" },
  mt_12: { marginTop: "3rem" },
  mt_16: { marginTop: "4rem" },
  mt_2: { marginTop: "0.5rem" },
  mt_20: { marginTop: "5rem" },
  mt_24: { marginTop: "6rem" },
  mt_3: { marginTop: "0.75rem" },
  mt_32: { marginTop: "8rem" },
  mt_4: { marginTop: "1rem" },
  mt_40: { marginTop: "10rem" },
  mt_48: { marginTop: "12rem" },
  mt_5: { marginTop: "1.25rem" },
  mt_56: { marginTop: "14rem" },
  mt_6: { marginTop: "1.5rem" },
  mt_64: { marginTop: "16rem" },
  mt_8: { marginTop: "2rem" },
  mt_auto: { marginTop: "auto" },
  mt_px: { marginTop: "1px" },
  mx_0: { marginLeft: "0", marginRight: "0" },
  mx_1: { marginLeft: "0.25rem", marginRight: "0.25rem" },
  mx_10: { marginLeft: "2.5rem", marginRight: "2.5rem" },
  mx_12: { marginLeft: "3rem", marginRight: "3rem" },
  mx_16: { marginLeft: "4rem", marginRight: "4rem" },
  mx_2: { marginLeft: "0.5rem", marginRight: "0.5rem" },
  mx_20: { marginLeft: "5rem", marginRight: "5rem" },
  mx_24: { marginLeft: "6rem", marginRight: "6rem" },
  mx_3: { marginLeft: "0.75rem", marginRight: "0.75rem" },
  mx_32: { marginLeft: "8rem", marginRight: "8rem" },
  mx_4: { marginLeft: "1rem", marginRight: "1rem" },
  mx_40: { marginLeft: "10rem", marginRight: "10rem" },
  mx_48: { marginLeft: "12rem", marginRight: "12rem" },
  mx_5: { marginLeft: "1.25rem", marginRight: "1.25rem" },
  mx_56: { marginLeft: "14rem", marginRight: "14rem" },
  mx_6: { marginLeft: "1.5rem", marginRight: "1.5rem" },
  mx_64: { marginLeft: "16rem", marginRight: "16rem" },
  mx_8: { marginLeft: "2rem", marginRight: "2rem" },
  mx_auto: { marginLeft: "auto", marginRight: "auto" },
  mx_px: { marginLeft: "1px", marginRight: "1px" },
  my_0: { marginTop: "0", marginBottom: "0" },
  my_1: { marginTop: "0.25rem", marginBottom: "0.25rem" },
  my_10: { marginTop: "2.5rem", marginBottom: "2.5rem" },
  my_12: { marginTop: "3rem", marginBottom: "3rem" },
  my_16: { marginTop: "4rem", marginBottom: "4rem" },
  my_2: { marginTop: "0.5rem", marginBottom: "0.5rem" },
  my_20: { marginTop: "5rem", marginBottom: "5rem" },
  my_24: { marginTop: "6rem", marginBottom: "6rem" },
  my_3: { marginTop: "0.75rem", marginBottom: "0.75rem" },
  my_32: { marginTop: "8rem", marginBottom: "8rem" },
  my_4: { marginTop: "1rem", marginBottom: "1rem" },
  my_40: { marginTop: "10rem", marginBottom: "10rem" },
  my_48: { marginTop: "12rem", marginBottom: "12rem" },
  my_5: { marginTop: "1.25rem", marginBottom: "1.25rem" },
  my_56: { marginTop: "14rem", marginBottom: "14rem" },
  my_6: { marginTop: "1.5rem", marginBottom: "1.5rem" },
  my_64: { marginTop: "16rem", marginBottom: "16rem" },
  my_8: { marginTop: "2rem", marginBottom: "2rem" },
  my_auto: { marginTop: "auto", marginBottom: "auto" },
  my_px: { marginTop: "1px", marginBottom: "1px" },
  no_underline: { textDecoration: "none" },
  normal_case: { textTransform: "none" },
  not_italic: { fontStyle: "normal" },
  not_sr_only: {
    position: "static",
    width: "auto",
    height: "auto",
    padding: "0",
    margin: "0",
    overflow: "visible",
    clip: "auto",
    whiteSpace: "normal"
  },
  object_bottom: { objectPosition: "bottom" },
  object_center: { objectPosition: "center" },
  object_contain: { objectFit: "contain" },
  object_cover: { objectFit: "cover" },
  object_fill: { objectFit: "fill" },
  object_left: { objectPosition: "left" },
  object_left_bottom: { objectPosition: "left bottom" },
  object_left_top: { objectPosition: "left top" },
  object_none: { objectFit: "none" },
  object_right: { objectPosition: "right" },
  object_right_bottom: { objectPosition: "right bottom" },
  object_right_top: { objectPosition: "right top" },
  object_scale_down: { objectFit: "scale-down" },
  object_top: { objectPosition: "top" },
  opacity_0: { opacity: "0" },
  opacity_100: { opacity: "1" },
  opacity_25: { opacity: "0.25" },
  opacity_50: { opacity: "0.5" },
  opacity_75: { opacity: "0.75" },
  order_1: { WebkitBoxOrdinalGroup: "2", order: "1" },
  order_10: { WebkitBoxOrdinalGroup: "11", order: "10" },
  order_11: { WebkitBoxOrdinalGroup: "12", order: "11" },
  order_12: { WebkitBoxOrdinalGroup: "13", order: "12" },
  order_2: { WebkitBoxOrdinalGroup: "3", order: "2" },
  order_3: { WebkitBoxOrdinalGroup: "4", order: "3" },
  order_4: { WebkitBoxOrdinalGroup: "5", order: "4" },
  order_5: { WebkitBoxOrdinalGroup: "6", order: "5" },
  order_6: { WebkitBoxOrdinalGroup: "7", order: "6" },
  order_7: { WebkitBoxOrdinalGroup: "8", order: "7" },
  order_8: { WebkitBoxOrdinalGroup: "9", order: "8" },
  order_9: { WebkitBoxOrdinalGroup: "10", order: "9" },
  order_first: { WebkitBoxOrdinalGroup: "-9998", order: "-9999" },
  order_last: { WebkitBoxOrdinalGroup: "10000", order: "9999" },
  order_none: { WebkitBoxOrdinalGroup: "1", order: "0" },
  outline_none: { outline: "0" },
  overflow_auto: { overflow: "auto" },
  overflow_hidden: { overflow: "hidden" },
  overflow_scroll: { overflow: "scroll" },
  overflow_visible: { overflow: "visible" },
  overflow_x_auto: { overflowX: "auto" },
  overflow_x_hidden: { overflowX: "hidden" },
  overflow_x_scroll: { overflowX: "scroll" },
  overflow_x_visible: { overflowX: "visible" },
  overflow_y_auto: { overflowY: "auto" },
  overflow_y_hidden: { overflowY: "hidden" },
  overflow_y_scroll: { overflowY: "scroll" },
  overflow_y_visible: { overflowY: "visible" },
  p_0: { padding: "0" },
  p_1: { padding: "0.25rem" },
  p_10: { padding: "2.5rem" },
  p_12: { padding: "3rem" },
  p_16: { padding: "4rem" },
  p_2: { padding: "0.5rem" },
  p_20: { padding: "5rem" },
  p_24: { padding: "6rem" },
  p_3: { padding: "0.75rem" },
  p_32: { padding: "8rem" },
  p_4: { padding: "1rem" },
  p_40: { padding: "10rem" },
  p_48: { padding: "12rem" },
  p_5: { padding: "1.25rem" },
  p_56: { padding: "14rem" },
  p_6: { padding: "1.5rem" },
  p_64: { padding: "16rem" },
  p_8: { padding: "2rem" },
  p_px: { padding: "1px" },
  pb_0: { paddingBottom: "0" },
  pb_1: { paddingBottom: "0.25rem" },
  pb_10: { paddingBottom: "2.5rem" },
  pb_12: { paddingBottom: "3rem" },
  pb_16: { paddingBottom: "4rem" },
  pb_2: { paddingBottom: "0.5rem" },
  pb_20: { paddingBottom: "5rem" },
  pb_24: { paddingBottom: "6rem" },
  pb_3: { paddingBottom: "0.75rem" },
  pb_32: { paddingBottom: "8rem" },
  pb_4: { paddingBottom: "1rem" },
  pb_40: { paddingBottom: "10rem" },
  pb_48: { paddingBottom: "12rem" },
  pb_5: { paddingBottom: "1.25rem" },
  pb_56: { paddingBottom: "14rem" },
  pb_6: { paddingBottom: "1.5rem" },
  pb_64: { paddingBottom: "16rem" },
  pb_8: { paddingBottom: "2rem" },
  pb_px: { paddingBottom: "1px" },
  pl_0: { paddingLeft: "0" },
  pl_1: { paddingLeft: "0.25rem" },
  pl_10: { paddingLeft: "2.5rem" },
  pl_12: { paddingLeft: "3rem" },
  pl_16: { paddingLeft: "4rem" },
  pl_2: { paddingLeft: "0.5rem" },
  pl_20: { paddingLeft: "5rem" },
  pl_24: { paddingLeft: "6rem" },
  pl_3: { paddingLeft: "0.75rem" },
  pl_32: { paddingLeft: "8rem" },
  pl_4: { paddingLeft: "1rem" },
  pl_40: { paddingLeft: "10rem" },
  pl_48: { paddingLeft: "12rem" },
  pl_5: { paddingLeft: "1.25rem" },
  pl_56: { paddingLeft: "14rem" },
  pl_6: { paddingLeft: "1.5rem" },
  pl_64: { paddingLeft: "16rem" },
  pl_8: { paddingLeft: "2rem" },
  pl_px: { paddingLeft: "1px" },
  pointer_events_auto: { pointerEvents: "auto" },
  pointer_events_none: { pointerEvents: "none" },
  pr_0: { paddingRight: "0" },
  pr_1: { paddingRight: "0.25rem" },
  pr_10: { paddingRight: "2.5rem" },
  pr_12: { paddingRight: "3rem" },
  pr_16: { paddingRight: "4rem" },
  pr_2: { paddingRight: "0.5rem" },
  pr_20: { paddingRight: "5rem" },
  pr_24: { paddingRight: "6rem" },
  pr_3: { paddingRight: "0.75rem" },
  pr_32: { paddingRight: "8rem" },
  pr_4: { paddingRight: "1rem" },
  pr_40: { paddingRight: "10rem" },
  pr_48: { paddingRight: "12rem" },
  pr_5: { paddingRight: "1.25rem" },
  pr_56: { paddingRight: "14rem" },
  pr_6: { paddingRight: "1.5rem" },
  pr_64: { paddingRight: "16rem" },
  pr_8: { paddingRight: "2rem" },
  pr_px: { paddingRight: "1px" },
  pt_0: { paddingTop: "0" },
  pt_1: { paddingTop: "0.25rem" },
  pt_10: { paddingTop: "2.5rem" },
  pt_12: { paddingTop: "3rem" },
  pt_16: { paddingTop: "4rem" },
  pt_2: { paddingTop: "0.5rem" },
  pt_20: { paddingTop: "5rem" },
  pt_24: { paddingTop: "6rem" },
  pt_3: { paddingTop: "0.75rem" },
  pt_32: { paddingTop: "8rem" },
  pt_4: { paddingTop: "1rem" },
  pt_40: { paddingTop: "10rem" },
  pt_48: { paddingTop: "12rem" },
  pt_5: { paddingTop: "1.25rem" },
  pt_56: { paddingTop: "14rem" },
  pt_6: { paddingTop: "1.5rem" },
  pt_64: { paddingTop: "16rem" },
  pt_8: { paddingTop: "2rem" },
  pt_px: { paddingTop: "1px" },
  px_0: { paddingLeft: "0", paddingRight: "0" },
  px_1: { paddingLeft: "0.25rem", paddingRight: "0.25rem" },
  px_10: { paddingLeft: "2.5rem", paddingRight: "2.5rem" },
  px_12: { paddingLeft: "3rem", paddingRight: "3rem" },
  px_16: { paddingLeft: "4rem", paddingRight: "4rem" },
  px_2: { paddingLeft: "0.5rem", paddingRight: "0.5rem" },
  px_20: { paddingLeft: "5rem", paddingRight: "5rem" },
  px_24: { paddingLeft: "6rem", paddingRight: "6rem" },
  px_3: { paddingLeft: "0.75rem", paddingRight: "0.75rem" },
  px_32: { paddingLeft: "8rem", paddingRight: "8rem" },
  px_4: { paddingLeft: "1rem", paddingRight: "1rem" },
  px_40: { paddingLeft: "10rem", paddingRight: "10rem" },
  px_48: { paddingLeft: "12rem", paddingRight: "12rem" },
  px_5: { paddingLeft: "1.25rem", paddingRight: "1.25rem" },
  px_56: { paddingLeft: "14rem", paddingRight: "14rem" },
  px_6: { paddingLeft: "1.5rem", paddingRight: "1.5rem" },
  px_64: { paddingLeft: "16rem", paddingRight: "16rem" },
  px_8: { paddingLeft: "2rem", paddingRight: "2rem" },
  px_px: { paddingLeft: "1px", paddingRight: "1px" },
  py_0: { paddingTop: "0", paddingBottom: "0" },
  py_1: { paddingTop: "0.25rem", paddingBottom: "0.25rem" },
  py_10: { paddingTop: "2.5rem", paddingBottom: "2.5rem" },
  py_12: { paddingTop: "3rem", paddingBottom: "3rem" },
  py_16: { paddingTop: "4rem", paddingBottom: "4rem" },
  py_2: { paddingTop: "0.5rem", paddingBottom: "0.5rem" },
  py_20: { paddingTop: "5rem", paddingBottom: "5rem" },
  py_24: { paddingTop: "6rem", paddingBottom: "6rem" },
  py_3: { paddingTop: "0.75rem", paddingBottom: "0.75rem" },
  py_32: { paddingTop: "8rem", paddingBottom: "8rem" },
  py_4: { paddingTop: "1rem", paddingBottom: "1rem" },
  py_40: { paddingTop: "10rem", paddingBottom: "10rem" },
  py_48: { paddingTop: "12rem", paddingBottom: "12rem" },
  py_5: { paddingTop: "1.25rem", paddingBottom: "1.25rem" },
  py_56: { paddingTop: "14rem", paddingBottom: "14rem" },
  py_6: { paddingTop: "1.5rem", paddingBottom: "1.5rem" },
  py_64: { paddingTop: "16rem", paddingBottom: "16rem" },
  py_8: { paddingTop: "2rem", paddingBottom: "2rem" },
  py_px: { paddingTop: "1px", paddingBottom: "1px" },
  relative: { position: "relative" },
  resize: { resize: "both" },
  resize_none: { resize: "none" },
  resize_x: { resize: "horizontal" },
  resize_y: { resize: "vertical" },
  right_0: { right: "0" },
  right_auto: { right: "auto" },
  rounded: { borderRadius: "0.25rem" },
  rounded_b: {
    borderBottomRightRadius: "0.25rem",
    borderBottomLeftRadius: "0.25rem"
  },
  rounded_b_full: {
    borderBottomRightRadius: "9999px",
    borderBottomLeftRadius: "9999px"
  },
  rounded_b_lg: {
    borderBottomRightRadius: "0.5rem",
    borderBottomLeftRadius: "0.5rem"
  },
  rounded_b_none: { borderBottomRightRadius: "0", borderBottomLeftRadius: "0" },
  rounded_b_sm: {
    borderBottomRightRadius: "0.125rem",
    borderBottomLeftRadius: "0.125rem"
  },
  rounded_bl: { borderBottomLeftRadius: "0.25rem" },
  rounded_bl_full: { borderBottomLeftRadius: "9999px" },
  rounded_bl_lg: { borderBottomLeftRadius: "0.5rem" },
  rounded_bl_none: { borderBottomLeftRadius: "0" },
  rounded_bl_sm: { borderBottomLeftRadius: "0.125rem" },
  rounded_br: { borderBottomRightRadius: "0.25rem" },
  rounded_br_full: { borderBottomRightRadius: "9999px" },
  rounded_br_lg: { borderBottomRightRadius: "0.5rem" },
  rounded_br_none: { borderBottomRightRadius: "0" },
  rounded_br_sm: { borderBottomRightRadius: "0.125rem" },
  rounded_full: { borderRadius: "9999px" },
  rounded_l: {
    borderTopLeftRadius: "0.25rem",
    borderBottomLeftRadius: "0.25rem"
  },
  rounded_l_full: {
    borderTopLeftRadius: "9999px",
    borderBottomLeftRadius: "9999px"
  },
  rounded_l_lg: {
    borderTopLeftRadius: "0.5rem",
    borderBottomLeftRadius: "0.5rem"
  },
  rounded_l_none: { borderTopLeftRadius: "0", borderBottomLeftRadius: "0" },
  rounded_l_sm: {
    borderTopLeftRadius: "0.125rem",
    borderBottomLeftRadius: "0.125rem"
  },
  rounded_lg: { borderRadius: "0.5rem" },
  rounded_none: { borderRadius: "0" },
  rounded_r: {
    borderTopRightRadius: "0.25rem",
    borderBottomRightRadius: "0.25rem"
  },
  rounded_r_full: {
    borderTopRightRadius: "9999px",
    borderBottomRightRadius: "9999px"
  },
  rounded_r_lg: {
    borderTopRightRadius: "0.5rem",
    borderBottomRightRadius: "0.5rem"
  },
  rounded_r_none: { borderTopRightRadius: "0", borderBottomRightRadius: "0" },
  rounded_r_sm: {
    borderTopRightRadius: "0.125rem",
    borderBottomRightRadius: "0.125rem"
  },
  rounded_sm: { borderRadius: "0.125rem" },
  rounded_t: {
    borderTopLeftRadius: "0.25rem",
    borderTopRightRadius: "0.25rem"
  },
  rounded_t_full: {
    borderTopLeftRadius: "9999px",
    borderTopRightRadius: "9999px"
  },
  rounded_t_lg: {
    borderTopLeftRadius: "0.5rem",
    borderTopRightRadius: "0.5rem"
  },
  rounded_t_none: { borderTopLeftRadius: "0", borderTopRightRadius: "0" },
  rounded_t_sm: {
    borderTopLeftRadius: "0.125rem",
    borderTopRightRadius: "0.125rem"
  },
  rounded_tl: { borderTopLeftRadius: "0.25rem" },
  rounded_tl_full: { borderTopLeftRadius: "9999px" },
  rounded_tl_lg: { borderTopLeftRadius: "0.5rem" },
  rounded_tl_none: { borderTopLeftRadius: "0" },
  rounded_tl_sm: { borderTopLeftRadius: "0.125rem" },
  rounded_tr: { borderTopRightRadius: "0.25rem" },
  rounded_tr_full: { borderTopRightRadius: "9999px" },
  rounded_tr_lg: { borderTopRightRadius: "0.5rem" },
  rounded_tr_none: { borderTopRightRadius: "0" },
  rounded_tr_sm: { borderTopRightRadius: "0.125rem" },
  scrolling_auto: { WebkitOverflowScrolling: "auto" },
  scrolling_touch: { WebkitOverflowScrolling: "touch" },
  select_all: {
    WebkitUserSelect: "all",
    MozUserSelect: "all",
    msUserSelect: "all",
    userSelect: "all"
  },
  select_auto: {
    WebkitUserSelect: "auto",
    MozUserSelect: "auto",
    msUserSelect: "auto",
    userSelect: "auto"
  },
  select_none: {
    WebkitUserSelect: "none",
    MozUserSelect: "none",
    msUserSelect: "none",
    userSelect: "none"
  },
  select_text: {
    WebkitUserSelect: "text",
    MozUserSelect: "text",
    msUserSelect: "text",
    userSelect: "text"
  },
  self_auto: { alignSelf: "auto" },
  self_center: { alignSelf: "center" },
  self_end: { alignSelf: "flex-end" },
  self_start: { alignSelf: "flex-start" },
  self_stretch: { alignSelf: "stretch" },
  shadow: {
    boxShadow: "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)"
  },
  shadow_2xl: { boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.25)" },
  shadow_inner: { boxShadow: "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)" },
  shadow_lg: {
    boxShadow:
      "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)"
  },
  shadow_md: {
    boxShadow:
      "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)"
  },
  shadow_none: { boxShadow: "none" },
  shadow_outline: { boxShadow: "0 0 0 3px rgba(66, 153, 225, 0.5)" },
  shadow_xl: {
    boxShadow:
      "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)"
  },
  sr_only: {
    position: "absolute",
    width: "1px",
    height: "1px",
    padding: "0",
    margin: "-1px",
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    borderWidth: "0"
  },
  static: { position: "static" },
  sticky: { position: ["-webkit-sticky", "sticky"] },
  stroke_current: { stroke: "currentColor" },
  subpixel_antialiased: {
    WebkitFontSmoothing: "auto",
    MozOsxFontSmoothing: "auto"
  },
  table: { display: "table" },
  table_auto: { tableLayout: "auto" },
  table_cell: { display: "table-cell" },
  table_fixed: { tableLayout: "fixed" },
  table_row: { display: "table-row" },
  text_2xl: { fontSize: "1.5rem" },
  text_3xl: { fontSize: "1.875rem" },
  text_4xl: { fontSize: "2.25rem" },
  text_5xl: { fontSize: "3rem" },
  text_6xl: { fontSize: "4rem" },
  text_base: { fontSize: "1rem" },
  text_black: { color: "#000" },
  text_blue_100: { color: "#ebf8ff" },
  text_blue_200: { color: "#bee3f8" },
  text_blue_300: { color: "#90cdf4" },
  text_blue_400: { color: "#63b3ed" },
  text_blue_500: { color: "#4299e1" },
  text_blue_600: { color: "#3182ce" },
  text_blue_700: { color: "#2b6cb0" },
  text_blue_800: { color: "#2c5282" },
  text_blue_900: { color: "#2a4365" },
  text_center: { textAlign: "center" },
  text_gray_100: { color: "#f7fafc" },
  text_gray_200: { color: "#edf2f7" },
  text_gray_300: { color: "#e2e8f0" },
  text_gray_400: { color: "#cbd5e0" },
  text_gray_500: { color: "#a0aec0" },
  text_gray_600: { color: "#718096" },
  text_gray_700: { color: "#4a5568" },
  text_gray_800: { color: "#2d3748" },
  text_gray_900: { color: "#1a202c" },
  text_green_100: { color: "#f0fff4" },
  text_green_200: { color: "#c6f6d5" },
  text_green_300: { color: "#9ae6b4" },
  text_green_400: { color: "#68d391" },
  text_green_500: { color: "#48bb78" },
  text_green_600: { color: "#38a169" },
  text_green_700: { color: "#2f855a" },
  text_green_800: { color: "#276749" },
  text_green_900: { color: "#22543d" },
  text_indigo_100: { color: "#ebf4ff" },
  text_indigo_200: { color: "#c3dafe" },
  text_indigo_300: { color: "#a3bffa" },
  text_indigo_400: { color: "#7f9cf5" },
  text_indigo_500: { color: "#667eea" },
  text_indigo_600: { color: "#5a67d8" },
  text_indigo_700: { color: "#4c51bf" },
  text_indigo_800: { color: "#434190" },
  text_indigo_900: { color: "#3c366b" },
  text_justify: { textAlign: "justify" },
  text_left: { textAlign: "left" },
  text_lg: { fontSize: "1.125rem" },
  text_orange_100: { color: "#fffaf0" },
  text_orange_200: { color: "#feebc8" },
  text_orange_300: { color: "#fbd38d" },
  text_orange_400: { color: "#f6ad55" },
  text_orange_500: { color: "#ed8936" },
  text_orange_600: { color: "#dd6b20" },
  text_orange_700: { color: "#c05621" },
  text_orange_800: { color: "#9c4221" },
  text_orange_900: { color: "#7b341e" },
  text_pink_100: { color: "#fff5f7" },
  text_pink_200: { color: "#fed7e2" },
  text_pink_300: { color: "#fbb6ce" },
  text_pink_400: { color: "#f687b3" },
  text_pink_500: { color: "#ed64a6" },
  text_pink_600: { color: "#d53f8c" },
  text_pink_700: { color: "#b83280" },
  text_pink_800: { color: "#97266d" },
  text_pink_900: { color: "#702459" },
  text_purple_100: { color: "#faf5ff" },
  text_purple_200: { color: "#e9d8fd" },
  text_purple_300: { color: "#d6bcfa" },
  text_purple_400: { color: "#b794f4" },
  text_purple_500: { color: "#9f7aea" },
  text_purple_600: { color: "#805ad5" },
  text_purple_700: { color: "#6b46c1" },
  text_purple_800: { color: "#553c9a" },
  text_purple_900: { color: "#44337a" },
  text_red_100: { color: "#fff5f5" },
  text_red_200: { color: "#fed7d7" },
  text_red_300: { color: "#feb2b2" },
  text_red_400: { color: "#fc8181" },
  text_red_500: { color: "#f56565" },
  text_red_600: { color: "#e53e3e" },
  text_red_700: { color: "#c53030" },
  text_red_800: { color: "#9b2c2c" },
  text_red_900: { color: "#742a2a" },
  text_right: { textAlign: "right" },
  text_sm: { fontSize: "0.875rem" },
  text_teal_100: { color: "#e6fffa" },
  text_teal_200: { color: "#b2f5ea" },
  text_teal_300: { color: "#81e6d9" },
  text_teal_400: { color: "#4fd1c5" },
  text_teal_500: { color: "#38b2ac" },
  text_teal_600: { color: "#319795" },
  text_teal_700: { color: "#2c7a7b" },
  text_teal_800: { color: "#285e61" },
  text_teal_900: { color: "#234e52" },
  text_transparent: { color: "transparent" },
  text_white: { color: "#fff" },
  text_xl: { fontSize: "1.25rem" },
  text_xs: { fontSize: "0.75rem" },
  text_yellow_100: { color: "#fffff0" },
  text_yellow_200: { color: "#fefcbf" },
  text_yellow_300: { color: "#faf089" },
  text_yellow_400: { color: "#f6e05e" },
  text_yellow_500: { color: "#ecc94b" },
  text_yellow_600: { color: "#d69e2e" },
  text_yellow_700: { color: "#b7791f" },
  text_yellow_800: { color: "#975a16" },
  text_yellow_900: { color: "#744210" },
  top_0: { top: "0" },
  top_auto: { top: "auto" },
  tracking_normal: { letterSpacing: "0" },
  tracking_tight: { letterSpacing: "-0.025em" },
  tracking_tighter: { letterSpacing: "-0.05em" },
  tracking_wide: { letterSpacing: "0.025em" },
  tracking_wider: { letterSpacing: "0.05em" },
  tracking_widest: { letterSpacing: "0.1em" },
  truncate: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap"
  },
  underline: { textDecoration: "underline" },
  uppercase: { textTransform: "uppercase" },
  visible: { visibility: "visible" },
  w_0: { width: "0" },
  w_1: { width: "0.25rem" },
  "w_1\\/12": { width: "8.333333%" },
  "w_1\\/2": { width: "50%" },
  "w_1\\/3": { width: "33.333333%" },
  "w_1\\/4": { width: "25%" },
  "w_1\\/5": { width: "20%" },
  "w_1\\/6": { width: "16.666667%" },
  w_10: { width: "2.5rem" },
  "w_10\\/12": { width: "83.333333%" },
  "w_11\\/12": { width: "91.666667%" },
  w_12: { width: "3rem" },
  w_16: { width: "4rem" },
  w_2: { width: "0.5rem" },
  "w_2\\/12": { width: "16.666667%" },
  "w_2\\/3": { width: "66.666667%" },
  "w_2\\/4": { width: "50%" },
  "w_2\\/5": { width: "40%" },
  "w_2\\/6": { width: "33.333333%" },
  w_20: { width: "5rem" },
  w_24: { width: "6rem" },
  w_3: { width: "0.75rem" },
  "w_3\\/12": { width: "25%" },
  "w_3\\/4": { width: "75%" },
  "w_3\\/5": { width: "60%" },
  "w_3\\/6": { width: "50%" },
  w_32: { width: "8rem" },
  w_4: { width: "1rem" },
  "w_4\\/12": { width: "33.333333%" },
  "w_4\\/5": { width: "80%" },
  "w_4\\/6": { width: "66.666667%" },
  w_40: { width: "10rem" },
  w_48: { width: "12rem" },
  w_5: { width: "1.25rem" },
  "w_5\\/12": { width: "41.666667%" },
  "w_5\\/6": { width: "83.333333%" },
  w_56: { width: "14rem" },
  w_6: { width: "1.5rem" },
  "w_6\\/12": { width: "50%" },
  w_64: { width: "16rem" },
  "w_7\\/12": { width: "58.333333%" },
  w_8: { width: "2rem" },
  "w_8\\/12": { width: "66.666667%" },
  "w_9\\/12": { width: "75%" },
  w_auto: { width: "auto" },
  w_full: { width: "100%" },
  w_px: { width: "1px" },
  w_screen: { width: "100vw" },
  whitespace_no_wrap: { whiteSpace: "nowrap" },
  whitespace_normal: { whiteSpace: "normal" },
  whitespace_pre: { whiteSpace: "pre" },
  whitespace_pre_line: { whiteSpace: "pre-line" },
  whitespace_pre_wrap: { whiteSpace: "pre-wrap" },
  z_0: { zIndex: "0" },
  z_10: { zIndex: "10" },
  z_20: { zIndex: "20" },
  z_30: { zIndex: "30" },
  z_40: { zIndex: "40" },
  z_50: { zIndex: "50" },
  z_auto: { zIndex: "auto" }
};

export const tokens = (tokensUntyped as unknown) as Record<
  keyof typeof tokensUntyped,
  ObjectInterpolation<undefined>
>;
